import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import {
  Users, TrendingUp, Percent, Layers, FileText, ChevronDown,
  LogIn, UserPlus, CheckCircle2,
} from 'lucide-react'
import { useTheme } from '../context/ThemeContext'
import Navbar from '../components/Navbar'
import PageHeader from '../components/shared/PageHeader'
import { commissionTiers } from '../affiliate/commissionTiers'

// ── Static content ───────────────────────────────────────────────────────────
// This is copy-only content for now. If you later want this editable from an
// admin panel, move these arrays into src/data/affiliates.js and fetch from
// `GET /api/affiliates/content` the same way Events/Promotions/Poker do.

const benefits = [
  { icon: TrendingUp, title: 'Recurring Revenue', text: 'Earn lifetime commission on every referred player\'s activity, not just a one-time payout.' },
  { icon: Percent,    title: 'Tiered Commission', text: 'Commission rates increase automatically as your referred player volume grows.' },
  { icon: Layers,     title: 'Multi-Casino Reach', text: 'Promote our full network of partner casinos, events, and promotions under one affiliate account.' },
  { icon: Users,      title: 'Dedicated Support', text: 'A dedicated affiliate manager to help with marketing assets, tracking, and payouts.' },
]

const howItWorks = [
  { step: '01', title: 'Register', text: 'Create your affiliate account in minutes — no upfront cost.' },
  { step: '02', title: 'Share Your Link', text: 'Get a unique tracking link and promotional assets for your audience.' },
  { step: '03', title: 'Refer Players', text: 'Every signup and deposit through your link is tracked automatically.' },
  { step: '04', title: 'Get Paid', text: 'Commissions are calculated monthly and paid out directly to your account.' },
]

const terms = [
  'Affiliates must be 18 years or older and comply with all applicable local laws.',
  'Self-referrals and fraudulent traffic are strictly prohibited and will result in account termination.',
  'Commission is calculated on net revenue generated by referred players, reviewed monthly.',
  'Jackpots World reserves the right to adjust commission tiers or terminate the program with notice.',
  'Payouts are processed monthly, subject to a minimum payout threshold.',
]

const faqs = [
  { q: 'Is there a cost to join the affiliate program?', a: 'No — joining the Jackpots World affiliate program is completely free.' },
  { q: 'How and when do I get paid?', a: 'Commissions are calculated monthly based on your referred players\' activity and paid out directly to your registered account.' },
  { q: 'Can I promote more than one partner casino?', a: 'Yes — your affiliate link covers our entire network of partner casinos, events, and promotions.' },
  { q: 'Is there a limit to how much I can earn?', a: 'There is no cap on commission earnings. The more active players you refer, the higher your tier and payout.' },
]

function FaqItem({ faq, isOpen, onToggle }) {
  return (
    <div className="casino-card overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-5 py-4 text-left"
      >
        <span className="font-body text-sm md:text-base text-white/85 font-semibold pr-4">{faq.q}</span>
        <motion.span animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }} className="text-gold shrink-0">
          <ChevronDown size={18} />
        </motion.span>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <p className="px-5 pb-4 text-white/55 text-sm font-body leading-relaxed">{faq.a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

/**
 * Affiliates page
 *
 * Informational + CTA page today. Once affiliate accounts exist on the
 * backend, an authenticated affiliate should land on a dashboard (referral
 * users, referral earnings, commission history, performance stats) instead
 * of this marketing view — e.g. redirect logged-in affiliates to
 * `/affiliates/dashboard` and keep this page as the public-facing pitch for
 * everyone else.
 */
export default function Affiliates() {
  const [openFaq, setOpenFaq]   = useState(0)
  const navigate = useNavigate()
  const { theme } = useTheme()

  return (
    <div key={theme} className="min-h-screen" style={{ background: 'var(--w365-bg)' }}>
      <Navbar />

      <PageHeader
        eyebrow="Partner With Us"
        title="Jackpots World Affiliates"
        subtitle="Turn your audience into recurring revenue by referring players across our entire network of luxury partner casinos."
      />

      {/* What is it */}
      <section className="max-w-4xl mx-auto px-4 pb-16 text-center">
        <p className="text-white/60 font-body text-sm md:text-base leading-relaxed">
          The Jackpots World Affiliate Program lets creators, publishers, and communities earn ongoing
          commission by referring players to our network of luxury partner casinos, events, and
          promotions. No inventory, no risk — just a tracking link and a dedicated affiliate manager
          to help you grow.
        </p>
      </section>

      {/* Benefits */}
      <section className="max-w-7xl mx-auto px-4 pb-20">
        <h2 className="gold-text font-black text-2xl text-center mb-10 tracking-wide">Why Become an Affiliate</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {benefits.map(({ icon: Icon, title, text }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="casino-card p-6 text-center flex flex-col items-center gap-3"
            >
              <div
                className="w-11 h-11 rounded-full flex items-center justify-center"
                style={{ background: 'rgba(212,175,55,0.12)', border: '1px solid rgba(212,175,55,0.4)' }}
              >
                <Icon size={18} className="text-gold" />
              </div>
              <h3 className="font-body font-bold text-sm text-white/85">{title}</h3>
              <p className="text-white/50 text-xs font-body leading-relaxed">{text}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Commission structure */}
      <section className="max-w-5xl mx-auto px-4 pb-20">
        <h2 className="gold-text font-black text-2xl text-center mb-10 tracking-wide">Commission Structure</h2>
        <div className="casino-card overflow-hidden">
          <div className="grid grid-cols-3 px-5 py-3 text-xs uppercase tracking-widest text-gold/70 font-body font-bold" style={{ borderBottom: '1px solid rgba(212,175,55,0.15)' }}>
            <span>Tier</span>
            <span>Active Referrals</span>
            <span>Commission Rate</span>
          </div>
          {commissionTiers.map((row, i) => (
            <div
              key={row.tier}
              className="grid grid-cols-3 px-5 py-4 text-sm font-body text-white/70"
              style={{ borderBottom: i < commissionTiers.length - 1 ? '1px solid rgba(212,175,55,0.08)' : 'none' }}
            >
              <span className="font-bold text-white/85">{row.tier}</span>
              <span>{row.referrals}</span>
              <span className="text-gold font-semibold">{row.rate}</span>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="max-w-6xl mx-auto px-4 pb-20">
        <h2 className="gold-text font-black text-2xl text-center mb-10 tracking-wide">How It Works</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {howItWorks.map((step, i) => (
            <motion.div
              key={step.step}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="casino-card p-6 flex flex-col gap-2"
            >
              <span className="gold-text font-black text-3xl">{step.step}</span>
              <h3 className="font-body font-bold text-sm text-white/85">{step.title}</h3>
              <p className="text-white/50 text-xs font-body leading-relaxed">{step.text}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Terms & Conditions */}
      <section className="max-w-4xl mx-auto px-4 pb-20">
        <h2 className="gold-text font-black text-2xl text-center mb-10 tracking-wide flex items-center justify-center gap-2">
          <FileText size={20} className="text-gold" /> Terms &amp; Conditions
        </h2>
        <div className="casino-card p-6">
          <ul className="flex flex-col gap-3">
            {terms.map((t, i) => (
              <li key={i} className="flex items-start gap-2.5 text-white/55 text-sm font-body leading-relaxed">
                <CheckCircle2 size={15} className="text-gold shrink-0 mt-0.5" />
                {t}
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-4xl mx-auto px-4 pb-20">
        <h2 className="gold-text font-black text-2xl text-center mb-10 tracking-wide">Frequently Asked Questions</h2>
        <div className="flex flex-col gap-3">
          {faqs.map((faq, i) => (
            <FaqItem
              key={i}
              faq={faq}
              isOpen={openFaq === i}
              onToggle={() => setOpenFaq(openFaq === i ? -1 : i)}
            />
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-3xl mx-auto px-4 pb-24 text-center">
        <div className="section-divider max-w-xs mx-auto mb-8" />
        <h2 className="gold-text font-black text-2xl mb-3 tracking-wide">Ready to Start Earning?</h2>
        <p className="text-white/55 font-body text-sm mb-8">
          Join the Jackpots World Affiliate Program today — it's free, and your dashboard is ready the moment you sign up.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate('/affiliate-login')}
            className="btn-outline-gold flex items-center gap-2 px-8 py-3 rounded-full text-sm font-bold tracking-widest uppercase"
          >
            <LogIn size={15} /> Affiliate Login
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate('/affiliate-register')}
            className="btn-gold flex items-center gap-2 px-8 py-3 rounded-full text-sm font-bold tracking-widest uppercase"
          >
            <UserPlus size={15} /> Become an Affiliate
          </motion.button>
        </div>
      </section>
    </div>
  )
}
