"""
authapp/utils/bot_detection.py
─────────────────────────────────────────────────────────────────────────────
ANALYTICS: best-effort, documented bot / non-human filtering.

Deliberately conservative — it only drops traffic that self-identifies as
automated (its User-Agent names a known crawler / tool / monitor, or is empty).
It does NOT attempt behavioural detection: a wrong guess that drops a real
visitor is worse for "real analytics generated by actual users" than letting an
occasional bot slip through, and the spec explicitly does not want an
unreliable "perfect bot detector".

Detection rules actually implemented (and nothing beyond them):
  1. Empty User-Agent  → treated as non-human. Real browsers always send one;
     the app's own health check (/healthz/) and most scripts send none.
  2. User-Agent matching the known-automation pattern below (crawlers, search
     engines, link unfurlers, headless browsers, HTTP libraries, uptime
     monitors, performance scanners).
"""
import re

_BOT_RE = re.compile(
    r"bot|crawl|spider|slurp|bingpreview|mediapartners|adsbot|"
    r"facebookexternalhit|facebot|ia_archiver|semrush|ahrefs|mj12|dotbot|"
    r"headlesschrome|phantomjs|puppeteer|playwright|selenium|"
    r"curl|wget|python-requests|python-urllib|go-http-client|okhttp|libwww|"
    r"axios/|node-fetch|httpclient|scrapy|apache-httpclient|"
    r"uptime|pingdom|monitor|statuscake|newrelic|datadog|site24x7|"
    r"lighthouse|gtmetrix|pagespeed|google-inspectiontool",
    re.I,
)


def is_bot(user_agent: str) -> bool:
    """True if this request should be excluded from human engagement counts."""
    ua = (user_agent or "").strip()
    if not ua:
        return True
    return bool(_BOT_RE.search(ua))
