# Generated by Django 5.2.12 on 2026-07-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('ticket_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventTicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_requests', to='authapp.casinoevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PokerTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poker/')),
                ('name', models.CharField(max_length=200)),
                ('casino_name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('seats_available', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poker_tournaments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='PokerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_registrations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='authapp.pokertournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('casino_name', models.CharField(blank=True, max_length=150)),
                ('casino_logo', models.ImageField(blank=True, null=True, upload_to='promotions/logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('validity_text', models.CharField(blank=True, max_length=150)),
                ('bonus_details', models.CharField(blank=True, max_length=300)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(default='Claim Bonus', max_length=60)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='casinoevent',
            index=models.Index(fields=['is_active', 'event_date'], name='authapp_cas_is_acti_3fb5b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventticketrequest',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='pokertournament',
            index=models.Index(fields=['is_active', 'event_date'], name='authapp_pok_is_acti_a30ab6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pokerregistration',
            unique_together={('tournament', 'user')},
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'country'], name='authapp_pro_is_acti_f40b56_idx'),
        ),
    ]
