# Generated by Django 5.2.12 on 2026-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_casinoevent_eventticketrequest_pokertournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='casino',
            unique_together={('country', 'name')},
        ),
    ]
