# Generated by Django 5.2.12 on 2026-07-06 12:34

from django.db import migrations

COUNTRIES = ["India", "Sri Lanka", "Vietnam", "Macau", "Philippines"]

CASINOS = [
    # Group 1
    "Ballys Casino", "Bellagio Casino", "Casino Marina", "Majestic Pride",
    "City of Dreams", "Deltin Royale", "Deltin Jaqk", "Big Daddy",
    "Casino Pride", "Kings Casino", "Atlantiz",
    # Group 2
    "Ocean 7", "Phoenix Casino", "Majestic Neo", "Gold Casino",
    "Mahjong", "Deltin Denzong", "Casino Corona", "Casino Grand",
    "Casino Crown", "Wynn Palace", "The Parisian",
    # Group 3
    "The Venetian", "Galaxy", "MGM", "Sands Macao",
    "Grand Lisboa", "Wynn Macau", "StarWorld", "L'Arc",
    "Okada Manila", "Solaire Resorts & Casino", "Resorts World",
]


def seed_casinos(apps, schema_editor):
    Casino = apps.get_model("authapp", "Casino")
    rows = [
        Casino(country=country, name=name, is_active=True)
        for country in COUNTRIES
        for name in CASINOS
    ]
    Casino.objects.bulk_create(rows, ignore_conflicts=True)


def remove_seeded_casinos(apps, schema_editor):
    Casino = apps.get_model("authapp", "Casino")
    Casino.objects.filter(country__in=COUNTRIES, name__in=CASINOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_casino_name_alter_casino_unique_together'),
    ]

    operations = [
        migrations.RunPython(seed_casinos, remove_seeded_casinos),
    ]
