# Generated by Django 5.2.12 on 2026-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_affiliateprofile_referralcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinowalletaccount',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='casinowalletaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
