# Generated by Django 5.2.12 on 2026-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_fix_casino_country_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinowalletaccount',
            name='rolling_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
