# Generated by Django 5.2.12 on 2026-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_add_casino_wallet_rolling_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticketrequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventticketrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='eventticketrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pokerregistration',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokerregistration',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='pokerregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
