# Generated by Django 5.2.12 on 2026-07-07 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('cash_wallet_bonus', 'Cash Wallet Bonus'), ('casino_wallet_bonus', 'Casino Wallet Bonus'), ('rolling_points', 'Free Rolling Points'), ('cashback', 'Cashback'), ('bonus_credits', 'Bonus Credits (Non-Cash)'), ('merch', 'Merchandise/Gift'), ('event_pass', 'Event Pass'), ('tournament_entry', 'Free Tournament Entry'), ('jackpot_bonus', 'Jackpot Bonus'), ('vip_upgrade', 'VIP Upgrade'), ('discount_coupon', 'Discount Coupon')], max_length=25)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('casino_name', models.CharField(blank=True, max_length=150)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('is_jackpot', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_jackpot', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='SpinGlobalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_spin_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type_snapshot', models.CharField(max_length=25)),
                ('reward_label_snapshot', models.CharField(max_length=100)),
                ('value_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_jackpot_win', models.BooleanField(default=False)),
                ('global_counter_value', models.PositiveBigIntegerField()),
                ('month_key', models.CharField(db_index=True, max_length=7)),
                ('needs_manual_fulfillment', models.BooleanField(db_index=True, default=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.spinconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spun_at'],
                'indexes': [models.Index(fields=['user', 'month_key'], name='authapp_spi_user_id_1d4554_idx')],
            },
        ),
    ]
