# Generated by Django 5.2.12 on 2026-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_affiliate_click_and_login_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
