# Generated by Django 5.2.12 on 2026-07-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_user_last_login_city_user_last_login_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_spins_per_month', models.PositiveIntegerField(default=5)),
                ('jackpot_every_n_users', models.PositiveIntegerField(default=50)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spinglobalcounter',
            name='eligible_spin_count',
        ),
        migrations.AddField(
            model_name='spinconfig',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.casinoevent'),
        ),
        migrations.AddField(
            model_name='spinconfig',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spinconfig',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.pokertournament'),
        ),
        migrations.AddField(
            model_name='spinglobalcounter',
            name='eligible_user_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spinconfig',
            name='reward_type',
            field=models.CharField(choices=[('cash_wallet_bonus', 'Cash Wallet Bonus'), ('casino_wallet_bonus', 'Casino Wallet Bonus'), ('rolling_points', 'Free Rolling Points'), ('cashback', 'Cashback'), ('bonus_credits', 'Bonus Credits (Non-Cash)'), ('merch', 'Merchandise'), ('gift_voucher', 'Gift Voucher'), ('discount_coupon', 'Discount Voucher'), ('event_pass', 'Event Pass'), ('tournament_entry', 'Free Tournament Entry'), ('jackpot_bonus', 'Jackpot Bonus'), ('vip_upgrade', 'VIP Upgrade'), ('no_reward', 'No Reward')], max_length=25),
        ),
        migrations.AlterField(
            model_name='usergift',
            name='gift_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('cashback', 'Cashback'), ('referral', 'Referral Bonus'), ('vip_upgrade', 'VIP Upgrade Gift'), ('tournament', 'Tournament Prize'), ('welcome', 'Welcome Bonus'), ('manual', 'Manual Gift'), ('merchandise', 'Merchandise'), ('gift_voucher', 'Gift Voucher'), ('discount_voucher', 'Discount Voucher'), ('spin_reward', 'Spin Wheel Reward')], default='manual', max_length=30),
        ),
    ]
