# Generated by Django 5.2.12 on 2026-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_seed_supported_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='kyc_type',
            field=models.CharField(choices=[('player', 'Player'), ('affiliate', 'Affiliate')], db_index=True, default='player', max_length=10),
        ),
    ]
