# Generated by Django 5.2.12 on 2026-07-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_adminprofile_theme_preference_kycsubmission_kyc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='promotions/videos/'),
        ),
        migrations.CreateModel(
            name='PromotionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='authapp.promotion')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
