# Generated by Django 5.2.12 on 2026-07-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_promotion_terms_conditions_promotion_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag_country_code', models.CharField(blank=True, max_length=8)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('casinos_text', models.CharField(blank=True, max_length=300)),
                ('best_for', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='ELITE', max_length=30)),
                ('tier_color', models.CharField(default='#D4AF37', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/gifts/')),
                ('value', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GiftStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎰', max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default="Asia's #1 Offline Casino's VIP's Platform", max_length=200)),
                ('hero_background_video', models.FileField(blank=True, null=True, upload_to='landing/')),
                ('hero_cta_primary_label', models.CharField(default='🎰 Register — FREE', max_length=60)),
                ('hero_cta_secondary_label', models.CharField(default='Packages ✨', max_length=60)),
                ('hero_tagline', models.CharField(default='www.jackpotsworld.casino', max_length=100)),
                ('global_reach_tagline', models.CharField(default='Experience World-Class Casino Gaming Across', max_length=200)),
                ('trust_banner_heading', models.CharField(default='Join 50,000+ Winning Players Across Asia', max_length=200)),
                ('trust_banner_subtext', models.TextField(blank=True, default='From first-time casino visitors to high-rollers — Jackpots World is your trusted partner for every bet.')),
                ('whatsapp_number', models.CharField(default='917795281999', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('amount_won', models.CharField(blank=True, max_length=40)),
                ('destination', models.CharField(blank=True, max_length=80)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='landing/testimonials/')),
                ('text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=30)),
                ('icon', models.CharField(default='🎰', max_length=10)),
                ('color', models.CharField(default='#D4AF37', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('duration', models.CharField(blank=True, max_length=40)),
                ('flight', models.CharField(blank=True, max_length=60)),
                ('hotel', models.CharField(blank=True, max_length=80)),
                ('food', models.CharField(blank=True, max_length=60)),
                ('liquor', models.CharField(blank=True, max_length=100)),
                ('airport_vip', models.BooleanField(default=False)),
                ('jackpot_rewards', models.BooleanField(default=False)),
                ('vip_transport', models.BooleanField(default=False)),
                ('vip_transport_note', models.CharField(blank=True, max_length=10)),
                ('spa', models.BooleanField(default=False)),
                ('spa_note', models.CharField(blank=True, max_length=10)),
                ('shopping_voucher', models.BooleanField(default=False)),
                ('shopping_note', models.CharField(blank=True, max_length=10)),
                ('visa', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(default='CheckCircle', max_length=40)),
                ('color', models.CharField(default='#34d399', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VipServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/vip-services/')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('accent_color', models.CharField(default='#1e3a8a', max_length=20)),
                ('accent_bg', models.CharField(default='#eff6ff', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(default='ShieldCheck', max_length=40)),
                ('color', models.CharField(default='#D4AF37', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DestinationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='landing/destinations/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authapp.destination')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VipTierBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='authapp.viptier')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
