# Generated by Django 5.2.12 on 2026-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_seed_landing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='can_view_player_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc/id_proof/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('address_proof', 'Address Proof'), ('income_proof', 'Income Proof')], max_length=30),
        ),
    ]
