# Generated by Django 5.2.12 on 2026-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_affiliateprofile_can_view_player_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_badge_text',
            field=models.CharField(default="Asia's #1 Offline Casinos VIP's Platform", max_length=200),
        ),
    ]
