# Generated by Django 5.2.12 on 2026-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_alter_landingsettings_hero_badge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spinconfig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spin/rewards/'),
        ),
    ]
