# Generated by Django 5.2.12 on 2026-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_notification_authapp_not_user_id_9ba27b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('wallet_adjusted', 'Wallet Adjusted'), ('deposit_created', 'Deposit Created'), ('withdrawal_created', 'Withdrawal Created'), ('casino_visit_recorded', 'Casino Visit Recorded'), ('casino_transfer', 'Casino Transfer'), ('rolling_points_rejected', 'Rolling Points Rejected'), ('bonus_added', 'Bonus Added'), ('reward_created', 'Reward Created'), ('reward_claimed', 'Reward Claimed'), ('vip_upgraded', 'VIP Upgraded'), ('vip_downgraded', 'VIP Downgraded'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('notification_sent', 'Notification Sent'), ('staff_created', 'Staff Created'), ('settings_changed', 'Settings Changed'), ('other', 'Other')], max_length=50),
        ),
    ]
