# Generated by Django 5.2.12 on 2026-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('translation_provider', models.CharField(choices=[('mock', 'Mock (offline, no external calls)'), ('openai', 'OpenAI'), ('aws_translate', 'AWS Translate'), ('google_translate', 'Google Cloud Translate')], default='mock', max_length=20)),
                ('fallback_language', models.CharField(default='en', max_length=8)),
                ('auto_detect_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply_translated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='message_translated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='preferred_language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
