# Generated by Django 5.2.12 on 2026-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0032_supportsettings_supportticket_admin_reply_translated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_tagline',
            field=models.CharField(default='www.jackpotsworld.vip', max_length=100),
        ),
    ]
