# Generated by Django 5.2.12 on 2026-07-22 10:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0033_alter_landingsettings_hero_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateWithdrawalMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('is_enabled', models.BooleanField(default=False)),
                ('field_schema', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateWithdrawalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_withdrawal_enabled', models.BooleanField(default=True)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=14)),
                ('estimated_processing_time_text', models.CharField(default='1–3 business days', max_length=100)),
                ('processing_notes', models.TextField(blank=True, default='Withdrawals are reviewed manually and paid out via USDT. Double-check your wallet address and network before submitting — payments sent to an incorrect address cannot be recovered.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateWalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('locked_for_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reference', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('txn_hash', models.CharField(blank=True, max_length=200)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='authapp.affiliatewithdrawalmethodconfig')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_withdrawals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateWithdrawalPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(default=dict)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.affiliatewithdrawalmethodconfig')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='authapp.affiliatewithdrawalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('EARNED', 'Commission Earned'), ('LOCKED', 'Locked For Withdrawal'), ('UNLOCKED', 'Unlocked (Rejected/Cancelled)'), ('PAID', 'Withdrawal Paid')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authapp.affiliatewalletaccount')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='authapp.affiliatewithdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateWithdrawalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_withdrawal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='authapp.affiliatewithdrawalrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='affiliatewithdrawalrequest',
            index=models.Index(fields=['affiliate', 'status'], name='authapp_aff_affilia_cd296d_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatewithdrawalrequest',
            index=models.Index(fields=['status', 'requested_at'], name='authapp_aff_status_a82dea_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatewallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='authapp_aff_wallet__6478c7_idx'),
        ),
    ]
