# Generated by Django 5.2.12 on 2026-07-22 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0035_affiliate_withdrawal_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRequestMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('is_enabled', models.BooleanField(default=False)),
                ('field_schema', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('wallet_adjusted', 'Wallet Adjusted'), ('deposit_created', 'Deposit Created'), ('withdrawal_created', 'Withdrawal Created'), ('casino_visit_recorded', 'Casino Visit Recorded'), ('casino_transfer', 'Casino Transfer'), ('rolling_points_rejected', 'Rolling Points Rejected'), ('bonus_added', 'Bonus Added'), ('reward_created', 'Reward Created'), ('reward_claimed', 'Reward Claimed'), ('vip_upgraded', 'VIP Upgraded'), ('vip_downgraded', 'VIP Downgraded'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('notification_sent', 'Notification Sent'), ('staff_created', 'Staff Created'), ('settings_changed', 'Settings Changed'), ('two_factor_enabled', 'Two-Factor Enabled'), ('two_factor_disabled', 'Two-Factor Disabled'), ('affiliate_withdrawal_requested', 'Affiliate Withdrawal Requested'), ('affiliate_withdrawal_cancelled', 'Affiliate Withdrawal Cancelled'), ('affiliate_withdrawal_processing', 'Affiliate Withdrawal Moved To Processing'), ('affiliate_withdrawal_approved', 'Affiliate Withdrawal Approved'), ('affiliate_withdrawal_rejected', 'Affiliate Withdrawal Rejected'), ('affiliate_withdrawal_paid', 'Affiliate Withdrawal Paid'), ('main_deposit_requested', 'Deposit Request Submitted'), ('main_deposit_processing', 'Deposit Request Moved To Processing'), ('main_deposit_approved', 'Deposit Request Approved'), ('main_deposit_rejected', 'Deposit Request Rejected'), ('main_deposit_cancelled', 'Deposit Request Cancelled'), ('main_withdrawal_requested', 'Withdrawal Request Submitted'), ('main_withdrawal_processing', 'Withdrawal Request Moved To Processing'), ('main_withdrawal_approved', 'Withdrawal Request Approved'), ('main_withdrawal_rejected', 'Withdrawal Request Rejected'), ('main_withdrawal_paid', 'Withdrawal Request Paid'), ('main_withdrawal_cancelled', 'Withdrawal Request Cancelled'), ('gift_admin_created', 'Gift Created By Admin'), ('gift_expired', 'Gift Expired By Admin'), ('gift_cancelled', 'Gift Cancelled By Admin'), ('gift_reissued', 'Gift Reissued By Admin'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usergift',
            name='gift_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('cashback', 'Cashback'), ('referral', 'Referral Bonus'), ('vip_upgrade', 'VIP Upgrade Gift'), ('tournament', 'Tournament Prize'), ('welcome', 'Welcome Bonus'), ('manual', 'Manual Gift'), ('merchandise', 'Merchandise'), ('gift_voucher', 'Gift Voucher'), ('discount_voucher', 'Discount Voucher'), ('spin_reward', 'Spin Wheel Reward'), ('registration', 'Registration Reward'), ('birthday', 'Birthday Gift'), ('festival', 'Festival Gift'), ('event', 'Event Reward'), ('lucky_draw', 'Lucky Draw Reward'), ('coupon', 'Coupon Reward'), ('loyalty', 'Loyalty Reward'), ('achievement', 'Achievement Reward'), ('seasonal', 'Seasonal Reward')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reference', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests', to='authapp.casino')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_request', to='authapp.wallettransaction')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='authapp.walletrequestmethodconfig')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='authapp.depositrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reference', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('wallet_type', models.CharField(default='C', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='authapp.wallettransaction')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='authapp.withdrawalrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['user', 'status'], name='authapp_dep_user_id_dceabe_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['status', 'requested_at'], name='authapp_dep_status_686b15_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='authapp_wit_user_id_f82428_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'requested_at'], name='authapp_wit_status_162704_idx'),
        ),
    ]
