# Generated by Django 5.2.12 on 2026-07-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_support_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='casino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='authapp.casino'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='authapp.walletrequestmethodconfig'),
        ),
    ]
