# Generated by Django 5.2.12 on 2026-08-06 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0040_wallet_request_methods_bank_cash_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateclicklog',
            name='browser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='device',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AffiliateCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('campaign_id', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_logs', to='authapp.affiliatecampaign'),
        ),
        migrations.AddIndex(
            model_name='affiliateclicklog',
            index=models.Index(fields=['campaign', 'created_at'], name='authapp_aff_campaig_73a82c_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecampaign',
            index=models.Index(fields=['affiliate', 'status'], name='authapp_aff_affilia_514996_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatecampaign',
            unique_together={('affiliate', 'campaign_id')},
        ),
    ]
