# Generated by Django 5.2.12 on 2026-08-07 10:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0041_affiliate_campaigns_and_click_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCommissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePlayerCommissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('deposit', 'Deposit Commission'), ('losing', 'Losing Commission'), ('rolling', 'Rolling Commission')], db_index=True, max_length=10)),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('deposit_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('required_wagering', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('completed_wagering', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('player_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rolling_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('qualification_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], db_index=True, default='pending', max_length=15)),
                ('not_qualified_reason', models.CharField(blank=True, max_length=255)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('deposit', 'Deposit Commission'), ('losing', 'Losing Commission'), ('rolling', 'Rolling Commission')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14)),
                ('wagering_multiplier', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text="Shown to the affiliate as the plain-language explanation of this plan's terms.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['commission_type', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='commission_type',
            field=models.CharField(choices=[('legacy', 'Legacy Flat Rate'), ('deposit', 'Deposit Commission'), ('losing', 'Losing Commission'), ('rolling', 'Rolling Commission')], db_index=True, default='legacy', max_length=10),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='completed_wagering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='not_qualified_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='player_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='qualification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], default='qualified', max_length=15),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='required_wagering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['affiliate', 'commission_type'], name='authapp_ref_affilia_179ca3_idx'),
        ),
        migrations.AddField(
            model_name='affiliatecommissionassignment',
            name='affiliate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatecommissionassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateplayercommissionstatus',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_commission_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateplayercommissionstatus',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_status_source', to='authapp.referralcommission'),
        ),
        migrations.AddField(
            model_name='affiliateplayercommissionstatus',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateplayercommissionstatus',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_statuses', to='authapp.commissionplan'),
        ),
        migrations.AddField(
            model_name='affiliatecommissionassignment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authapp.commissionplan'),
        ),
        migrations.AddIndex(
            model_name='affiliateplayercommissionstatus',
            index=models.Index(fields=['affiliate', 'qualification_status'], name='authapp_aff_affilia_ad2391_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateplayercommissionstatus',
            index=models.Index(fields=['affiliate', 'commission_type'], name='authapp_aff_affilia_de65e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliateplayercommissionstatus',
            unique_together={('affiliate', 'referred_user', 'commission_type')},
        ),
    ]
