# Generated by Django 5.2.12 on 2026-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0043_seed_default_commission_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
