# Generated by Django 5.2.12 on 2026-08-07 19:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0044_widen_referral_commission_rate_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupWheelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('cash_bonus', 'Cash Bonus'), ('cashback', 'Cashback'), ('rolling_points', 'Rolling Points'), ('vip_points', 'VIP Points'), ('gift_voucher', 'Gift Voucher'), ('merchandise', 'Merchandise'), ('hotel_stay', 'Hotel Stay'), ('event_ticket', 'Event Ticket'), ('casino_coupon', 'Casino Coupon'), ('free_travel', 'Free Travel'), ('discount', 'Discount'), ('free_spins', 'Free Spins'), ('physical_gift', 'Physical Gift'), ('mystery_reward', 'Mystery Reward'), ('no_reward', 'Try Again')], default='cash_bonus', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('probability_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('no_repeat_for_player', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheel/signup_rewards/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='usergift',
            name='gift_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('cashback', 'Cashback'), ('referral', 'Referral Bonus'), ('vip_upgrade', 'VIP Upgrade Gift'), ('tournament', 'Tournament Prize'), ('welcome', 'Welcome Bonus'), ('manual', 'Manual Gift'), ('merchandise', 'Merchandise'), ('gift_voucher', 'Gift Voucher'), ('discount_voucher', 'Discount Voucher'), ('spin_reward', 'Spin Wheel Reward'), ('registration', 'Registration Reward'), ('birthday', 'Birthday Gift'), ('festival', 'Festival Gift'), ('event', 'Event Reward'), ('lucky_draw', 'Lucky Draw Reward'), ('coupon', 'Coupon Reward'), ('loyalty', 'Loyalty Reward'), ('achievement', 'Achievement Reward'), ('seasonal', 'Seasonal Reward'), ('hotel_stay', 'Hotel Stay'), ('free_travel', 'Free Travel'), ('physical_gift', 'Physical Gift')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='BonusWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('campaign_tag', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('theme', models.CharField(default='gold_black', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_wheels_created', to=settings.AUTH_USER_MODEL)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.casinoevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusWheelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('individual', 'Individual Player(s)'), ('vip_level', 'VIP Level'), ('country', 'Country'), ('event_registrants', 'Event Registrants')], max_length=20)),
                ('target_vip_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_country', models.CharField(blank=True, max_length=2)),
                ('spins_granted', models.PositiveIntegerField(default=1)),
                ('grant_reason', models.CharField(choices=[('vip_levelup', 'VIP Level-Up'), ('birthday', 'Birthday'), ('loyalty', 'Loyalty Reward'), ('promotional', 'Promotional Event'), ('compensation', 'Compensation'), ('special_campaign', 'Special Campaign'), ('losing_streak', 'Losing-Streak Reward'), ('winning_milestone', 'Winning Milestone'), ('other', 'Other')], default='other', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_wheel_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.casinoevent')),
                ('target_users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authapp.bonuswheel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusWheelGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spins_total', models.PositiveIntegerField()),
                ('spins_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authapp.bonuswheelassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_wheel_grants', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authapp.bonuswheel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusWheelReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('cash_bonus', 'Cash Bonus'), ('cashback', 'Cashback'), ('rolling_points', 'Rolling Points'), ('vip_points', 'VIP Points'), ('gift_voucher', 'Gift Voucher'), ('merchandise', 'Merchandise'), ('hotel_stay', 'Hotel Stay'), ('event_ticket', 'Event Ticket'), ('casino_coupon', 'Casino Coupon'), ('free_travel', 'Free Travel'), ('discount', 'Discount'), ('free_spins', 'Free Spins'), ('physical_gift', 'Physical Gift'), ('mystery_reward', 'Mystery Reward'), ('no_reward', 'Try Again')], default='cash_bonus', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('casino_name', models.CharField(blank=True, max_length=150)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheel/bonus_rewards/')),
                ('is_mystery', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('allow_repeat', models.BooleanField(default=True)),
                ('max_winners', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.casinoevent')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='authapp.bonuswheel')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BonusWheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_label_snapshot', models.CharField(max_length=100)),
                ('reward_type_snapshot', models.CharField(max_length=20)),
                ('value_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='authapp.bonuswheelgrant')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.bonuswheelreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_wheel_spins', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.bonuswheel')),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
        migrations.CreateModel(
            name='SignupWheelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_lifetime_spins', models.PositiveIntegerField(default=5)),
                ('eligibility_window_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignupWheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_label_snapshot', models.CharField(max_length=100)),
                ('reward_type_snapshot', models.CharField(max_length=20)),
                ('value_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spin_number', models.PositiveSmallIntegerField()),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authapp.signupwheelreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_wheel_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bonuswheelassignment',
            index=models.Index(fields=['wheel', 'created_at'], name='authapp_bon_wheel_i_38ab33_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuswheelgrant',
            index=models.Index(fields=['user', 'wheel'], name='authapp_bon_user_id_99171f_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuswheelgrant',
            index=models.Index(fields=['user', 'expires_at'], name='authapp_bon_user_id_9965dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuswheelspin',
            index=models.Index(fields=['user', 'spun_at'], name='authapp_bon_user_id_57a286_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuswheelspin',
            index=models.Index(fields=['reward', 'spun_at'], name='authapp_bon_reward__ef7405_idx'),
        ),
        migrations.AddIndex(
            model_name='signupwheelspin',
            index=models.Index(fields=['user', 'spun_at'], name='authapp_sig_user_id_8ef998_idx'),
        ),
    ]
