# Generated by Django 5.2.12 on 2026-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0046_seed_signup_wheel_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('wallet_adjusted', 'Wallet Adjusted'), ('deposit_created', 'Deposit Created'), ('withdrawal_created', 'Withdrawal Created'), ('casino_visit_recorded', 'Casino Visit Recorded'), ('casino_transfer', 'Casino Transfer'), ('rolling_points_rejected', 'Rolling Points Rejected'), ('bonus_added', 'Bonus Added'), ('reward_created', 'Reward Created'), ('reward_claimed', 'Reward Claimed'), ('vip_upgraded', 'VIP Upgraded'), ('vip_downgraded', 'VIP Downgraded'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('notification_sent', 'Notification Sent'), ('staff_created', 'Staff Created'), ('settings_changed', 'Settings Changed'), ('two_factor_enabled', 'Two-Factor Enabled'), ('two_factor_disabled', 'Two-Factor Disabled'), ('affiliate_withdrawal_requested', 'Affiliate Withdrawal Requested'), ('affiliate_withdrawal_cancelled', 'Affiliate Withdrawal Cancelled'), ('affiliate_withdrawal_processing', 'Affiliate Withdrawal Moved To Processing'), ('affiliate_withdrawal_approved', 'Affiliate Withdrawal Approved'), ('affiliate_withdrawal_rejected', 'Affiliate Withdrawal Rejected'), ('affiliate_withdrawal_paid', 'Affiliate Withdrawal Paid'), ('main_deposit_requested', 'Deposit Request Submitted'), ('main_deposit_processing', 'Deposit Request Moved To Processing'), ('main_deposit_approved', 'Deposit Request Approved'), ('main_deposit_rejected', 'Deposit Request Rejected'), ('main_deposit_cancelled', 'Deposit Request Cancelled'), ('main_withdrawal_requested', 'Withdrawal Request Submitted'), ('main_withdrawal_processing', 'Withdrawal Request Moved To Processing'), ('main_withdrawal_approved', 'Withdrawal Request Approved'), ('main_withdrawal_rejected', 'Withdrawal Request Rejected'), ('main_withdrawal_paid', 'Withdrawal Request Paid'), ('main_withdrawal_cancelled', 'Withdrawal Request Cancelled'), ('gift_admin_created', 'Gift Created By Admin'), ('gift_expired', 'Gift Expired By Admin'), ('gift_cancelled', 'Gift Cancelled By Admin'), ('gift_reissued', 'Gift Reissued By Admin'), ('wheel_bonus_wheel_created', 'Bonus Wheel Created Or Edited'), ('wheel_bonus_assigned', 'Bonus Wheel Assigned To Players'), ('other', 'Other')], max_length=50),
        ),
    ]
