# Generated by Django 5.2.12 on 2026-08-10 07:44
#
# Fixes a bug where a mid-cycle CommissionPlan.rate change on a "losing"
# plan retroactively re-priced a player's ENTIRE cumulative loss on their
# still-pending ReferralCommission row, not just newly-incurred loss —
# contrary to the service's own documented intent. See
# services/affiliate_commission_service._evaluate_losing() for the fix: it
# now prices only the loss beyond loss_basis_committed at the plan's current
# rate, then advances that basis by the same slice.
#
# The backfill below freezes loss_basis_committed at each existing "losing"
# status row's current player_loss — i.e. "everything already reflected in
# this player's commission figures as of right now" — so upgrading to the
# fixed code doesn't itself retroactively shift anyone's numbers; only loss
# incurred from this point forward is priced under the new, correct logic.

from decimal import Decimal
from django.db import migrations, models


def backfill_loss_basis_committed(apps, schema_editor):
    AffiliatePlayerCommissionStatus = apps.get_model('authapp', 'AffiliatePlayerCommissionStatus')
    AffiliatePlayerCommissionStatus.objects.filter(commission_type='losing').update(
        loss_basis_committed=models.F('player_loss')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0047_add_wheel_activitylog_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateplayercommissionstatus',
            name='loss_basis_committed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.RunPython(backfill_loss_basis_committed, migrations.RunPython.noop),
    ]
