# Generated by Django 5.2.12 on 2026-08-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0042_retire_old_whatsapp_number'),
        ('authapp', '0048_add_loss_basis_committed'),
    ]

    operations = [
    ]
