# Generated by Django 5.2.12 on 2026-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0053_add_kazakhstan_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='client_message_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='participant_type',
            field=models.CharField(choices=[('player', 'Player'), ('affiliate', 'Affiliate')], db_index=True, default='player', max_length=10),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['is_live_chat', 'participant_type', 'status'], name='authapp_sup_is_live_7b27a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('ticket', 'client_message_id'), name='uniq_chatmessage_ticket_client_id'),
        ),
    ]
