# Generated by Django 5.2.12 on 2026-08-14 10:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0054_live_chat_participant_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenPattiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teenpatti/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='teenpatti/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teen_patti_events', to='authapp.casino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teen_patti_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeenPattiRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=12)),
                ('entry_fee_at_registration', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('admin_note', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='authapp.teenpattievent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_patti_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teenpattievent',
            index=models.Index(fields=['is_active', 'status', 'start_date'], name='authapp_tee_is_acti_225f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='teenpattievent',
            index=models.Index(fields=['country', 'start_date'], name='authapp_tee_country_36295c_idx'),
        ),
        migrations.AddIndex(
            model_name='teenpattievent',
            index=models.Index(fields=['is_featured', 'start_date'], name='authapp_tee_is_feat_7f1e50_idx'),
        ),
        migrations.AddIndex(
            model_name='teenpattiregistration',
            index=models.Index(fields=['event', 'status'], name='authapp_tee_event_i_18b0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='teenpattiregistration',
            index=models.Index(fields=['user', 'created_at'], name='authapp_tee_user_id_0d19da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teenpattiregistration',
            unique_together={('event', 'user')},
        ),
    ]
