# Generated by Django 5.2.12 on 2026-08-14 11:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0055_teenpatti_events_and_registrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('commission_type', models.CharField(choices=[('deposit', 'Deposit Commission'), ('losing', 'Losing Commission'), ('rolling', 'Rolling Commission')], db_index=True, max_length=10)),
                ('rate_type', models.CharField(choices=[('percentage', 'Percentage of base amount'), ('fixed', 'Fixed amount per qualifying player'), ('tiered', 'Tiered — rate comes from the matching CommissionTier')], default='percentage', max_length=12)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Percent, used when rate_type is 'percentage'. 3dp so 0.115% is exact.", max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Used when rate_type is 'fixed'.", max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('min_qualifying_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Base amount must reach this before any commission is calculated.', max_digits=14)),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Optional ceiling applied to the calculated amount.', max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0)),
                ('specificity', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to=settings.AUTH_USER_MODEL)),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='authapp.casino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-specificity', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('referred_players', 'Referred players'), ('qualified_players', 'Qualified players'), ('active_players', 'Active players'), ('deposit_total', 'Total deposits'), ('deposit_per_player', 'Deposit per player'), ('betting_amount', 'Total betting amount'), ('rolling_points', 'Rolling points'), ('player_loss', 'Player loss'), ('active_days', 'Days player has been active')], max_length=24)),
                ('operator', models.CharField(choices=[('gte', '≥'), ('gt', '>'), ('lte', '≤'), ('lt', '<'), ('eq', '=')], default='gte', max_length=4)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='authapp.commissionrule')),
            ],
            options={
                'ordering': ['rule', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('metric', models.CharField(choices=[('referred_players', 'Referred players'), ('qualified_players', 'Qualified players'), ('active_players', 'Active players'), ('deposit_total', 'Total deposits'), ('deposit_per_player', 'Deposit per player'), ('betting_amount', 'Total betting amount'), ('rolling_points', 'Rolling points'), ('player_loss', 'Player loss'), ('active_days', 'Days player has been active')], default='qualified_players', max_length=24)),
                ('min_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='authapp.commissionrule')),
            ],
            options={
                'ordering': ['rule', 'order', 'min_value'],
            },
        ),
        migrations.CreateModel(
            name='CommissionLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('rule_name', models.CharField(blank=True, max_length=150)),
                ('tier_name', models.CharField(blank=True, max_length=120)),
                ('commission_type', models.CharField(choices=[('deposit', 'Deposit Commission'), ('losing', 'Losing Commission'), ('rolling', 'Rolling Commission')], db_index=True, max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('conditions_snapshot', models.JSONField(blank=True, default=list)),
                ('calculation_trace', models.TextField(blank=True)),
                ('qualification_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualifying', 'Qualifying'), ('qualified', 'Qualified'), ('approved', 'Approved'), ('payable', 'Payable'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_ledger_entries', to='authapp.casino')),
                ('referral_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='authapp.referralcommission')),
                ('referred_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_ledger_entries_generated', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries_reviewed', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='authapp.commissionrule')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='authapp.commissiontier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['is_active', 'commission_type', '-specificity'], name='authapp_com_is_acti_aaac10_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['country', 'commission_type'], name='authapp_com_country_d80d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['affiliate', 'commission_type'], name='authapp_com_affilia_4a20ad_idx'),
        ),
        migrations.AddIndex(
            model_name='commissioncondition',
            index=models.Index(fields=['rule', 'is_active'], name='authapp_com_rule_id_00df36_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontier',
            index=models.Index(fields=['rule', 'is_active', 'order'], name='authapp_com_rule_id_4dba8d_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['affiliate', 'status'], name='authapp_com_affilia_7fb86a_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['affiliate', 'commission_type'], name='authapp_com_affilia_d162bc_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['country', 'status'], name='authapp_com_country_f7eef9_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['status', 'created_at'], name='authapp_com_status_7c7ac4_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('affiliate', 'referred_player', 'commission_type', 'reference_id'), name='uniq_commission_ledger_reference'),
        ),
    ]
