# Generated by Django 5.2.12 on 2026-08-14 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0056_commission_rules_tiers_conditions_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Back Office entry'), ('rss', 'RSS / Atom feed'), ('json_api', 'Public JSON API'), ('ical', 'iCalendar feed')], default='rss', max_length=16)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('permission_note', models.TextField(blank=True, help_text='Why automated access to this source is permitted (ToS clause, API terms, agreement).')),
                ('last_attempted_sync', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('never', 'Never run'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='never', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PokerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=150)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('never', 'Never run'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='never', max_length=10)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='authapp.pokertournament'),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='game_type',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='official_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='organizer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='review_status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('archived', 'Archived')], db_index=True, default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poker_tournaments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='series',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PokerEventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poker_change_logs', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='authapp.pokertournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='authapp.pokersource'),
        ),
        migrations.AddIndex(
            model_name='pokertournament',
            index=models.Index(fields=['review_status', 'event_date'], name='authapp_pok_review__da2531_idx'),
        ),
        migrations.AddIndex(
            model_name='pokertournament',
            index=models.Index(fields=['country', 'event_date'], name='authapp_pok_country_465bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='pokertournament',
            index=models.Index(fields=['source', 'source_event_id'], name='authapp_pok_source__5ee456_idx'),
        ),
        migrations.AddField(
            model_name='pokersynclog',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='authapp.pokersource'),
        ),
        migrations.AddIndex(
            model_name='pokereventchangelog',
            index=models.Index(fields=['tournament', '-created_at'], name='authapp_pok_tournam_ec0349_idx'),
        ),
        migrations.AddIndex(
            model_name='pokersynclog',
            index=models.Index(fields=['source', '-started_at'], name='authapp_pok_source__705b3d_idx'),
        ),
    ]
