# Generated by Django 5.2.12 on 2026-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0058_backfill_poker_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('flag_country_code', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/partners/logos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/partners/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='landing/partners/')),
                ('partner_type', models.CharField(choices=[('top_premium', 'Top Premium Partner'), ('premium', 'Premium Partner'), ('standard', 'Standard Partner')], db_index=True, default='top_premium', max_length=20)),
                ('is_featured_in_hero', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'is_featured_in_hero', 'partner_type', 'order'], name='authapp_pre_is_acti_a6b197_idx')],
            },
        ),
    ]
