# Generated by Django 5.2.12 on 2026-08-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0059_premium_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('teen_patti', 'Teen Patti'), ('poker', 'Poker')], db_index=True, max_length=20)),
                ('slot', models.CharField(choices=[('side_left', 'Side Card — Left'), ('side_right', 'Side Card — Right'), ('background', 'Background Watermark')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('video', models.FileField(blank=True, null=True, upload_to='landing/section_media/')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='landing/section_media/posters/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'slot'],
                'unique_together': {('section', 'slot')},
            },
        ),
    ]
