# Generated by Django 5.2.12 on 2026-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0060_section_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpartner',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/partners/'),
        ),
        migrations.AlterField(
            model_name='premiumpartner',
            name='hero_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='landing/partners/'),
        ),
        migrations.AlterField(
            model_name='premiumpartner',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/partners/logos/'),
        ),
        migrations.AlterField(
            model_name='sectionmedia',
            name='poster_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/section_media/posters/'),
        ),
        migrations.AlterField(
            model_name='sectionmedia',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='landing/section_media/'),
        ),
    ]
