# Generated by Django 5.2.12 on 2026-08-17 18:20

import authapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0061_lengthen_media_filename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuswheelreward',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='wheel/bonus_rewards/'),
        ),
        migrations.AlterField(
            model_name='casinoevent',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='destinationmedia',
            name='media',
            field=models.FileField(max_length=255, upload_to='landing/destinations/'),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/gifts/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='doc_back',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_private_storage, upload_to='kyc/docs/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='doc_front',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_private_storage, upload_to='kyc/docs/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='id_proof_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_private_storage, upload_to='kyc/id_proof/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='selfie',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_private_storage, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_background_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='landing/'),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='poker/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='casino_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='promotions/logos/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='promotions/videos/'),
        ),
        migrations.AlterField(
            model_name='promotiongalleryimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='promotions/gallery/'),
        ),
        migrations.AlterField(
            model_name='signupwheelreward',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='wheel/signup_rewards/'),
        ),
        migrations.AlterField(
            model_name='spinconfig',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='spin/rewards/'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_private_storage, upload_to='support/attachments/'),
        ),
        migrations.AlterField(
            model_name='teenpattievent',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='teenpatti/banners/'),
        ),
        migrations.AlterField(
            model_name='teenpattievent',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='teenpatti/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/testimonials/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='vipserviceimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='landing/vip-services/'),
        ),
    ]
