# Generated by Django 5.2.12 on 2026-08-19 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0063_commission_ledger_reference_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('connected', 'Connected'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='ringing', max_length=12)),
                ('end_reason', models.CharField(blank=True, choices=[('caller_ended', 'Caller ended'), ('receiver_ended', 'Receiver ended'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('connection_failed', 'Connection failed'), ('permission_denied', 'Permission denied'), ('network_failure', 'Network failure')], default='', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ring_expires_at', models.DateTimeField(db_index=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('active_key', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='authapp.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connected', 'Connected'), ('mute', 'Mute'), ('unmute', 'Unmute'), ('ended', 'Ended'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, max_length=12)),
                ('detail', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authapp.callsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['ticket', '-created_at'], name='authapp_cal_ticket__f1d80a_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', '-created_at'], name='authapp_cal_caller__f16e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['receiver', '-created_at'], name='authapp_cal_receive_992d97_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', '-created_at'], name='authapp_cal_status_349774_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['created_at'], name='authapp_cal_created_8ef127_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.UniqueConstraint(fields=('active_key',), name='uniq_callsession_active_per_ticket'),
        ),
        migrations.AddIndex(
            model_name='callevent',
            index=models.Index(fields=['call', 'created_at'], name='authapp_cal_call_id_46377f_idx'),
        ),
    ]
