# Generated by Django 5.2.12 on 2026-08-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0064_voice_call_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDestinationShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='video', max_length=10)),
                ('media', models.FileField(blank=True, max_length=255, null=True, upload_to='landing/showcase/')),
                ('mobile_media', models.FileField(blank=True, max_length=255, null=True, upload_to='landing/showcase/')),
                ('poster_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/showcase/posters/')),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='authapp.destination')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='authapp_fea_is_acti_6a5025_idx')],
            },
        ),
    ]
