# Generated by Django 5.2.12 on 2026-08-19 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0065_featureddestinationshowcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=150)),
                ('utm_content', models.CharField(blank=True, max_length=150)),
                ('utm_term', models.CharField(blank=True, max_length=150)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('destination_url', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=10)),
                ('ad_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'utm_campaign'], name='authapp_cam_status_62400e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('url_click', 'URL Click'), ('video_start', 'Video Start'), ('video_progress', 'Video Progress'), ('video_complete', 'Video Complete'), ('signup', 'Signup'), ('login', 'Login')], db_index=True, max_length=32)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('content_id', models.CharField(blank=True, max_length=120)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=150)),
                ('utm_content', models.CharField(blank=True, max_length=150)),
                ('utm_term', models.CharField(blank=True, max_length=150)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('operating_system', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='authapp.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='authapp_ana_event_t_50bc0c_idx'), models.Index(fields=['content_type', 'content_id', 'event_type'], name='authapp_ana_content_71ab5b_idx'), models.Index(fields=['campaign', 'event_type', 'created_at'], name='authapp_ana_campaig_e6a9df_idx'), models.Index(fields=['utm_campaign', 'event_type'], name='authapp_ana_utm_cam_f5732d_idx'), models.Index(fields=['user', 'event_type'], name='authapp_ana_user_id_4e5386_idx'), models.Index(fields=['anonymous_id', 'event_type'], name='authapp_ana_anonymo_187a34_idx')],
            },
        ),
    ]
