# Generated by Django 5.2.17 on 2026-08-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0072_remove_150_percent_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='client_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('url_click', 'URL Click'), ('video_start', 'Video Start'), ('video_progress', 'Video Progress'), ('video_complete', 'Video Complete'), ('video_click', 'Video Click'), ('video_cta_click', 'Video CTA Click'), ('signup', 'Signup'), ('login', 'Login')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'event_type'], name='authapp_ana_session_276f70_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['country', 'event_type'], name='authapp_ana_country_9330eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsevent',
            constraint=models.UniqueConstraint(fields=('event_type', 'client_event_id'), name='uniq_analyticsevent_type_client_id'),
        ),
    ]
