# Generated by Django 5.2.12 on 2026-08-25 06:44

import authapp.models.call_models
import authapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0074_visitor_session_and_ip_location_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='recording',
            field=models.FileField(blank=True, max_length=255, null=True, storage=authapp.storage_backends.get_call_recording_storage, upload_to=authapp.models.call_models.call_recording_path),
        ),
        migrations.AddField(
            model_name='callsession',
            name='recording_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callsession',
            name='recording_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connected', 'Connected'), ('mute', 'Mute'), ('unmute', 'Unmute'), ('ended', 'Ended'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('recorded', 'Recorded')], db_index=True, max_length=12),
        ),
    ]
