# Generated by Django 5.2.12 on 2026-08-31 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0077_call_history_deleted_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('support', 'Support'), ('support_manager', 'Customer Support Manager'), ('finance', 'Finance'), ('kyc_officer', 'KYC Officer')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('caller_ended', 'Caller ended'), ('receiver_ended', 'Receiver ended'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('connection_failed', 'Connection failed'), ('permission_denied', 'Permission denied'), ('network_failure', 'Network failure'), ('no_agents', 'No agents available')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportAgentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support agent presence',
                'verbose_name_plural': 'Support agent presence',
                'indexes': [models.Index(fields=['user', '-connected_at'], name='authapp_sup_user_id_8f0cb0_idx')],
            },
        ),
    ]
