# Generated by Django 5.2.12 on 2026-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0078_support_manager_role_and_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Player to support'), ('outbound', 'Support callback')], db_index=True, default='inbound', max_length=10),
        ),
    ]
