# Generated by Django 5.2.12 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0080_business_model_wording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsettings',
            name='global_reach_tagline',
            field=models.CharField(default='Discover World-Class Casino Destinations Across', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_badge_text',
            field=models.CharField(default='Premium Offline Casino VIP Platform', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_cta_primary_label',
            field=models.CharField(default='Get Your Referral', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='hero_cta_secondary_label',
            field=models.CharField(default='Explore Packages', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='trust_banner_heading',
            field=models.CharField(default='Join 50,000+ Members Across Asia', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingsettings',
            name='trust_banner_subtext',
            field=models.TextField(blank=True, default='From first-time casino visitors to high-rollers — Jackpots World is your trusted partner for every trip.'),
        ),
    ]
