# Generated by Django 5.2.12 on 2026-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0081_landing_wording_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmedia',
            name='slot',
            field=models.CharField(choices=[('background', 'Background Watermark'), ('hero_card', 'Hero Media Card'), ('side_left', 'Side Card — Left (retired)'), ('side_right', 'Side Card — Right (retired)')], db_index=True, max_length=20),
        ),
    ]
