# Generated by Django 5.2.12 on 2026-09-07 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0084_why_choose_us_phrase_sweep'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndharBaharContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Card Game Experience', max_length=80)),
                ('hero_title', models.CharField(default='Andhar Bahar', max_length=160)),
                ('hero_subtitle', models.CharField(default='One card. Two sides. A decision in seconds.', max_length=200)),
                ('hero_description', models.TextField(default='Andhar Bahar is one of the fastest and most approachable card games on an Indian casino floor. We introduce members to the partner venues that run it, so the table is ready when you arrive.')),
                ('hero_cta_primary_label', models.CharField(default='Explore Andhar Bahar', max_length=60)),
                ('hero_cta_primary_link', models.CharField(default='#andhar-bahar-events', max_length=200)),
                ('hero_cta_secondary_label', models.CharField(default='Talk to a VIP Host', max_length=60)),
                ('hero_cta_secondary_link', models.CharField(default='/#contact', max_length=200)),
                ('hero_trust_text', models.CharField(default='Verified partner venues · Hosted introductions · Play at the casino, never online', max_length=200)),
                ('hero_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='andhar_bahar/')),
                ('intro_title', models.CharField(default='What Is Andhar Bahar?', max_length=160)),
                ('intro_body', models.TextField(default='Andhar Bahar is a traditional Indian card game played with a single deck. The dealer draws one joker card, then deals cards alternately to two sides — Andhar (inside) and Bahar (outside). Players back the side they believe will match the joker rank first. There is no hand to build and nothing to memorise, which is why a first-time visitor can follow a round immediately.')),
                ('how_to_play_title', models.CharField(default='How A Round Works', max_length=160)),
                ('how_to_play_note', models.CharField(default='Table rules, minimums and payouts are set by each casino — your host confirms them before you play.', max_length=300)),
                ('highlights_title', models.CharField(default='Why Players Enjoy It', max_length=160)),
                ('events_title', models.CharField(default='Andhar Bahar Destinations & Events', max_length=160)),
                ('events_subtitle', models.CharField(default='Partner casinos currently running Andhar Bahar tables, and the dates we are hosting members.', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('show_events_section', models.BooleanField(default=True)),
                ('show_highlights_section', models.BooleanField(default=True)),
                ('show_how_to_play_section', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Andhar Bahar content',
                'verbose_name_plural': 'Andhar Bahar content',
            },
        ),
        migrations.CreateModel(
            name='AndharBaharEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('min_buy_in', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='andhar_bahar/events/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AndharBaharHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(default='Zap', max_length=40)),
                ('color', models.CharField(default='#D4AF37', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AndharBaharStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CallHoldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('manual', 'Manual'), ('transfer', 'Transfer')], default='manual', max_length=12)),
                ('auto_resumed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('timeout', 'Timed out'), ('failed', 'Failed')], db_index=True, default='requested', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('ring_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('pending_key', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('landing', 'Landing Page'), ('affiliate', 'Affiliates Page'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='landing', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCommunicationRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('call', 'Calls')], db_index=True, max_length=8)),
                ('is_enabled', models.BooleanField(default=True)),
                ('disabled_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('admin_note', models.TextField(blank=True)),
                ('player_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCommunicationRestrictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('call', 'Calls')], db_index=True, max_length=8)),
                ('is_enabled', models.BooleanField()),
                ('disabled_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ring_timeout_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='voicecallsettings',
            options={'verbose_name': 'Live support settings', 'verbose_name_plural': 'Live support settings'},
        ),
        migrations.AddField(
            model_name='affiliateclicklog',
            name='game',
            field=models.CharField(blank=True, choices=[('', 'Any / Not game-specific'), ('poker', 'Poker'), ('teen_patti', 'Teen Patti'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='callsession',
            name='hold_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='is_on_hold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='is_transferring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='total_hold_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callsession',
            name='transfer_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionledgerentry',
            name='game',
            field=models.CharField(blank=True, choices=[('', 'Any / Not game-specific'), ('poker', 'Poker'), ('teen_patti', 'Teen Patti'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='game',
            field=models.CharField(blank=True, choices=[('', 'Any / Not game-specific'), ('poker', 'Poker'), ('teen_patti', 'Teen Patti'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='game',
            field=models.CharField(blank=True, choices=[('', 'Any / Not game-specific'), ('poker', 'Poker'), ('teen_patti', 'Teen Patti'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='call_disabled_message',
            field=models.CharField(default='Support calls are temporarily unavailable for your account. Please check back later.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='call_unavailable_message',
            field=models.CharField(default='Voice calling is not available right now. Please continue on chat and we will help you there.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='calls_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='chat_disabled_message',
            field=models.CharField(default='Support chat is temporarily unavailable for your account. Please check back later.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='forwarding_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='hold_audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='support/hold_audio/'),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='hold_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='hold_message',
            field=models.CharField(default='Please hold — your support agent will be back with you shortly.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='holiday_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='max_hold_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='offline_message',
            field=models.CharField(default='Support is currently offline. Leave a message and our team will reply as soon as we are back.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='queue_message',
            field=models.CharField(default='All our agents are busy right now. You are in the queue and will be connected shortly.', max_length=300),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='ring_timeout_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='transfer_ring_timeout_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicecallsettings',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('connected', 'Connected'), ('mute', 'Mute'), ('unmute', 'Unmute'), ('hold', 'Hold'), ('resume', 'Resume'), ('transfer', 'Transfer requested'), ('transferred', 'Transferred'), ('ended', 'Ended'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('recorded', 'Recorded')], db_index=True, max_length=12),
        ),
        migrations.AddIndex(
            model_name='commissionledgerentry',
            index=models.Index(fields=['affiliate', 'game'], name='authapp_com_affilia_fe1509_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['game', 'commission_type'], name='authapp_com_game_fff0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['affiliate', 'game'], name='authapp_ref_affilia_0f83b2_idx'),
        ),
        migrations.AddField(
            model_name='andharbaharcontent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='andharbaharevent',
            name='casino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andhar_bahar_events', to='authapp.casino'),
        ),
        migrations.AddField(
            model_name='andharbaharevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andhar_bahar_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callholdevent',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_events', to='authapp.callsession'),
        ),
        migrations.AddField(
            model_name='callholdevent',
            name='held_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callholdevent',
            name='resumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_transfers_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='authapp.callsession'),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='from_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_transfers_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playercommunicationrestriction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playercommunicationrestriction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playercommunicationrestrictionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playercommunicationrestrictionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_restriction_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportdepartment',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='support_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calltransfer',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_transfers', to='authapp.supportdepartment'),
        ),
        migrations.AddIndex(
            model_name='andharbaharevent',
            index=models.Index(fields=['is_active', 'status', 'start_date'], name='authapp_and_is_acti_0cfb13_idx'),
        ),
        migrations.AddIndex(
            model_name='andharbaharevent',
            index=models.Index(fields=['country', 'start_date'], name='authapp_and_country_eb9e97_idx'),
        ),
        migrations.AddIndex(
            model_name='andharbaharevent',
            index=models.Index(fields=['is_featured', 'start_date'], name='authapp_and_is_feat_2d76e7_idx'),
        ),
        migrations.AddIndex(
            model_name='callholdevent',
            index=models.Index(fields=['call', 'held_at'], name='authapp_cal_call_id_60f5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active', 'order'], name='authapp_faq_categor_1f4359_idx'),
        ),
        migrations.AddIndex(
            model_name='playercommunicationrestriction',
            index=models.Index(fields=['user', 'channel', 'is_enabled'], name='authapp_pla_user_id_66888a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playercommunicationrestriction',
            unique_together={('user', 'channel')},
        ),
        migrations.AddIndex(
            model_name='playercommunicationrestrictionlog',
            index=models.Index(fields=['user', '-created_at'], name='authapp_pla_user_id_1ce9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['call', 'status'], name='authapp_cal_call_id_3c9c34_idx'),
        ),
        migrations.AddIndex(
            model_name='calltransfer',
            index=models.Index(fields=['to_department', 'status'], name='authapp_cal_to_depa_bfd3f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='calltransfer',
            constraint=models.UniqueConstraint(fields=('pending_key',), name='uniq_call_transfer_pending'),
        ),
    ]
