# Generated by Django 5.2.12 on 2026-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0086_seed_andhar_bahar_faq_and_rescale_specificity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmedia',
            name='section',
            field=models.CharField(choices=[('teen_patti', 'Teen Patti'), ('poker', 'Poker'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, max_length=20),
        ),
    ]
