# Generated by Django 5.2.12 on 2026-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0087_andhar_bahar_section_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedepositlog',
            name='game',
            field=models.CharField(blank=True, choices=[('', 'Any / Not game-specific'), ('poker', 'Poker'), ('teen_patti', 'Teen Patti'), ('andhar_bahar', 'Andhar Bahar')], db_index=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offlinedepositlog',
            index=models.Index(fields=['game', 'created_at'], name='authapp_off_game_3fea49_idx'),
        ),
    ]
