# Generated by Django 5.2.12 on 2026-09-08 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0091_close_holds_on_ended_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndharBaharRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='authapp.andharbaharevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andhar_bahar_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='authapp_and_event_i_f90871_idx'), models.Index(fields=['user', 'created_at'], name='authapp_and_user_id_7b17b8_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
