# Generated by Django 5.2.12 on 2026-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0092_andhar_bahar_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='andharbaharcontent',
            name='signup_prompt',
            field=models.CharField(default='Interested in Andhar Bahar? Sign up to find out where the events are happening and where the tables are live.', max_length=300),
        ),
        migrations.AlterField(
            model_name='andharbaharcontent',
            name='hero_cta_primary_label',
            field=models.CharField(default='Sign Up For Updates', max_length=60),
        ),
        migrations.AlterField(
            model_name='andharbaharcontent',
            name='hero_cta_primary_link',
            field=models.CharField(default='/andhar-bahar/sign-up', max_length=200),
        ),
        migrations.AlterField(
            model_name='andharbaharcontent',
            name='hero_description',
            field=models.TextField(default='If you want to know where the events are happening and where the tables are live, sign up and we will tell you. Members get the dates, the venues and a VIP host to arrange the visit.'),
        ),
        migrations.AlterField(
            model_name='andharbaharcontent',
            name='hero_subtitle',
            field=models.CharField(default='Are you an Andhar Bahar player?', max_length=200),
        ),
    ]
