# Generated by Django 5.2.12 on 2026-09-09 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0094_andhar_bahar_signup_copy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('luxury_travel', 'Luxury Travel'), ('stay', 'Hotels & Resorts'), ('dining', 'Dining & Entertainment'), ('concierge', 'VIP Concierge')], db_index=True, help_text='Which landing-page section this appears in.', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('partner', models.CharField(blank=True, help_text='Only name a venue or operator once an arrangement is in place.', max_length=150)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='landing/experiences/')),
                ('video', models.FileField(blank=True, max_length=255, null=True, upload_to='landing/experiences/')),
                ('icon_name', models.CharField(blank=True, max_length=40)),
                ('accent_color', models.CharField(default='#D4AF37', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('cta_link', models.CharField(blank=True, max_length=300)),
                ('enquiry_key', models.SlugField(blank=True, help_text="EnquiryMessage key used for this card's WhatsApp handoff.", max_length=60)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, help_text='Leave empty for a service offered across the whole network.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='authapp.destination')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('luxury_travel', 'Luxury Travel'), ('stay', 'Hotels & Resorts'), ('dining', 'Dining & Entertainment'), ('concierge', 'VIP Concierge')], db_index=True, max_length=20)),
                ('experience_title', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('party_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='authapp.experience')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experience enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category', 'is_active', 'display_order'], name='authapp_exp_categor_e5c66f_idx'),
        ),
    ]
