# Generated by Django 5.2.12 on 2026-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0096_seed_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('overview', 'Beyond the Casino'), ('luxury_travel', 'Luxury Travel'), ('stay', 'Hotels & Resorts'), ('dining', 'Dining & Entertainment'), ('concierge', 'VIP Concierge')], db_index=True, help_text='Which landing-page section this appears in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='experienceenquiry',
            name='category',
            field=models.CharField(choices=[('overview', 'Beyond the Casino'), ('luxury_travel', 'Luxury Travel'), ('stay', 'Hotels & Resorts'), ('dining', 'Dining & Entertainment'), ('concierge', 'VIP Concierge')], db_index=True, max_length=20),
        ),
    ]
