# Generated by Django 5.2.12 on 2026-09-16 09:13

from django.db import migrations, models


def zeros_to_null(apps, schema_editor):
    """Legacy placeholder zeros become NULL.

    Before this migration both columns were NOT NULL with a default of 0, and
    the Back Office form omitted a blank number field from its multipart POST
    entirely — so "no buy-in was entered" and "the buy-in is zero" both landed
    in the database as 0 and were indistinguishable afterwards.

    Nothing has ever rendered that 0 as a price: the public Andhar Bahar card,
    the poker review table and the schema.org Offer in views/spa_seo.py all
    gate on `> 0` and show nothing below it. So rewriting these rows to NULL
    changes no page's output — it only makes the stored value say what was
    already being displayed, which is what lets the admin form show an empty
    box instead of a fabricated 0 when the event is reopened for editing.
    """
    apps.get_model("authapp", "PokerTournament").objects.filter(buy_in=0).update(buy_in=None)
    apps.get_model("authapp", "TeenPattiEvent").objects.filter(entry_fee=0).update(entry_fee=None)
    apps.get_model("authapp", "TeenPattiRegistration").objects.filter(
        entry_fee_at_registration=0
    ).update(entry_fee_at_registration=None)


def null_to_zeros(apps, schema_editor):
    """Restores the pre-migration representation so the AlterFields below can
    be unapplied against NOT NULL columns."""
    apps.get_model("authapp", "PokerTournament").objects.filter(buy_in__isnull=True).update(buy_in=0)
    apps.get_model("authapp", "TeenPattiEvent").objects.filter(entry_fee__isnull=True).update(entry_fee=0)
    apps.get_model("authapp", "TeenPattiRegistration").objects.filter(
        entry_fee_at_registration__isnull=True
    ).update(entry_fee_at_registration=0)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0098_seed_beyond_the_casino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertournament',
            name='buy_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='teenpattievent',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='teenpattiregistration',
            name='entry_fee_at_registration',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
        # Runs after the columns accept NULL, and is reversed before they stop
        # accepting it.
        migrations.RunPython(zeros_to_null, null_to_zeros),
    ]
