# Generated by Django 5.2.12 on 2026-09-17 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0099_optional_event_buy_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('all_recipients', models.JSONField(blank=True, default=list)),
                ('from_email', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('email_type', models.CharField(choices=[('otp_verification', 'Email Verification OTP'), ('otp_password_reset', 'Password Reset OTP'), ('affiliate_approval', 'Affiliate Approval'), ('affiliate_registration_alert', 'Affiliate Registration Alert'), ('other', 'Other / Untyped')], db_index=True, default='other', max_length=40)),
                ('triggered_by', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent / SMTP Accepted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=12)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=60)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('smtp_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='authapp.emaillog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='emaillog_created_idx'), models.Index(fields=['status', '-created_at'], name='emaillog_status_created_idx'), models.Index(fields=['email_type', '-created_at'], name='emaillog_type_created_idx'), models.Index(fields=['recipient_email', '-created_at'], name='emaillog_rcpt_created_idx'), models.Index(fields=['provider', '-created_at'], name='emaillog_provider_created_idx')],
            },
        ),
    ]
