# Generated by Django 5.2.17 on 2026-09-21 07:03
#
# FULL-ADMIN-AUDIT: gives ActivityLog the request-shaped columns the new
# audit middleware writes (endpoint / method / actor_type / status_code) and
# indexes the three ways the table is read.
#
# Safe to run against a live database, and cheap:
#   * All four columns are nullable with no default, so on MySQL 8 this is an
#     INSTANT metadata-only ALTER — no table copy, no long lock. Existing rows
#     keep NULL in the new columns, which is the honest value: nothing knew
#     the endpoint when they were written.
#   * The action ALTER is a choices= change. Django emits it because the
#     choice list grew, but choices are validation metadata, not schema — the
#     column stays varchar(50) and no data is touched.
#   * The four indexes are the only real work. They are added to a table that
#     is about to get much busier, which is the point of adding them now
#     rather than after it has.
#
# Reversible: `migrate authapp 0102` drops the columns and indexes. Doing so
# discards any audit detail recorded in the meantime, so treat the rollback as
# lossy even though the schema change itself is clean.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0102_seed_cruise_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('wallet_adjusted', 'Wallet Adjusted'), ('deposit_created', 'Deposit Created'), ('withdrawal_created', 'Withdrawal Created'), ('casino_visit_recorded', 'Casino Visit Recorded'), ('casino_transfer', 'Casino Transfer'), ('rolling_points_rejected', 'Rolling Points Rejected'), ('bonus_added', 'Bonus Added'), ('reward_created', 'Reward Created'), ('reward_claimed', 'Reward Claimed'), ('vip_upgraded', 'VIP Upgraded'), ('vip_downgraded', 'VIP Downgraded'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('notification_sent', 'Notification Sent'), ('staff_created', 'Staff Created'), ('settings_changed', 'Settings Changed'), ('call_history_deleted', 'Call History Deleted'), ('two_factor_enabled', 'Two-Factor Enabled'), ('two_factor_disabled', 'Two-Factor Disabled'), ('affiliate_withdrawal_requested', 'Affiliate Withdrawal Requested'), ('affiliate_withdrawal_cancelled', 'Affiliate Withdrawal Cancelled'), ('affiliate_withdrawal_processing', 'Affiliate Withdrawal Moved To Processing'), ('affiliate_withdrawal_approved', 'Affiliate Withdrawal Approved'), ('affiliate_withdrawal_rejected', 'Affiliate Withdrawal Rejected'), ('affiliate_withdrawal_paid', 'Affiliate Withdrawal Paid'), ('main_deposit_requested', 'Deposit Request Submitted'), ('main_deposit_processing', 'Deposit Request Moved To Processing'), ('main_deposit_approved', 'Deposit Request Approved'), ('main_deposit_rejected', 'Deposit Request Rejected'), ('main_deposit_cancelled', 'Deposit Request Cancelled'), ('main_withdrawal_requested', 'Withdrawal Request Submitted'), ('main_withdrawal_processing', 'Withdrawal Request Moved To Processing'), ('main_withdrawal_approved', 'Withdrawal Request Approved'), ('main_withdrawal_rejected', 'Withdrawal Request Rejected'), ('main_withdrawal_paid', 'Withdrawal Request Paid'), ('main_withdrawal_cancelled', 'Withdrawal Request Cancelled'), ('gift_admin_created', 'Gift Created By Admin'), ('gift_expired', 'Gift Expired By Admin'), ('gift_cancelled', 'Gift Cancelled By Admin'), ('gift_reissued', 'Gift Reissued By Admin'), ('wheel_bonus_wheel_created', 'Bonus Wheel Created Or Edited'), ('wheel_bonus_assigned', 'Bonus Wheel Assigned To Players'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('rolling_points_added', 'Rolling Points Added'), ('admin_create', 'Admin Created A Record'), ('admin_update', 'Admin Updated A Record'), ('admin_delete', 'Admin Deleted A Record'), ('admin_action', 'Admin Action'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='actlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', '-created_at'], name='actlog_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_user', '-created_at'], name='actlog_target_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='actlog_action_idx'),
        ),
    ]
