# Generated by Django 5.2.17 on 2026-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0105_relabel_admin_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpartner',
            name='show_as_partner',
            field=models.BooleanField(default=True),
        ),
    ]
