# Generated by Django 5.2.17 on 2026-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0106_premium_partner_show_as_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpartner',
            name='show_as_partner',
        ),
        migrations.AlterField(
            model_name='premiumpartner',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='premiumpartner',
            name='partner_type',
            field=models.CharField(choices=[('top_premium', 'Top Premium Partner'), ('premium', 'Premium Partner'), ('standard', 'Standard Partner'), ('others', 'Others')], db_index=True, default='top_premium', max_length=20),
        ),
    ]
