# WHATSAPP-CAPTURE: the lead captured on the near side of every wa.me handoff.
#
# New table only -- nothing existing is altered, so this is additive and safe
# to run against a live database. Reversing it drops the table and the leads
# in it, which is the one genuinely destructive thing in this change; there is
# no other copy, because a WhatsApp conversation cannot be read back from
# WhatsApp.
#
# See authapp/models/whatsapp_enquiry_models.py for why the capture happens
# before the handoff rather than after it.

# Generated by Django 5.2.17 on 2026-09-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0107_premium_partner_others_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('whatsapp_number', models.CharField(db_index=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=40)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('destination_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WhatsApp enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='waenq_status_idx')],
            },
        ),
    ]
