# WHATSAPP-LEADS: adds to the table 0108 creates so a press can be recorded
# even when the visitor gives no details, and so a lead says which button it
# came from in words rather than only as a slug.
#
# Purely additive and safe to run live:
#   * every new column is nullable-or-blank with no default backfill, so on
#     MySQL 8 this is an INSTANT metadata-only ALTER — no table copy, no lock;
#   * the status ALTER widens varchar(12) to varchar(20) to fit the reserved
#     "message_received" state. Widening a varchar in place is also instant and
#     cannot truncate anything;
#   * the three indexes are added before the table has volume, which is the
#     cheapest time to add them.
#
# Nothing existing is altered in meaning and no data is rewritten. 0108 has not
# reached production yet, so in practice both apply together on the next
# deploy.
#
# Reversible: dropping these columns loses the campaign attribution and click
# counts recorded in the meantime, but the leads themselves — name, number,
# message, button slug — live in 0108's columns and survive.

# Generated by Django 5.2.17 on 2026-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0108_whatsapp_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappenquiry',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='button_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='click_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='first_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='whatsappenquiry',
            name='status',
            field=models.CharField(choices=[('clicked', 'Clicked (no details given)'), ('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('message_received', 'Message received')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='whatsappenquiry',
            index=models.Index(fields=['-created_at'], name='waenq_created_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappenquiry',
            index=models.Index(fields=['source', '-created_at'], name='waenq_source_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappenquiry',
            index=models.Index(fields=['utm_campaign', '-created_at'], name='waenq_campaign_idx'),
        ),
    ]
