# WHATSAPP-LEADS: an optional email on the lead, and the per-button toggle that
# decides whether a logged-out visitor is asked for details before WhatsApp
# opens.
#
# Purely additive and safe to run live. Two nullable-or-defaulted columns, no
# data rewritten, nothing existing altered:
#
#   * whatsappenquiry.email    -- blank by default; existing rows simply have
#                                 no address, which is honest, because none was
#                                 ever collected for them.
#   * enquirymessage.capture_details -- default FALSE, which is what makes this
#                                 deploy invisible: every button keeps behaving
#                                 exactly as it does today until somebody turns
#                                 it on in Back Office.
#
# On MySQL 8 both are INSTANT metadata-only ALTERs -- no table copy, no lock.
# Reversing drops the two columns; any addresses collected in the meantime are
# lost with them, but the leads themselves (name, number, button) survive.

# Generated by Django 5.2.17 on 2026-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0109_whatsapp_enquiry_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirymessage',
            name='capture_details',
            field=models.BooleanField(default=False, help_text='Ask logged-out visitors for their name, WhatsApp number and email before opening WhatsApp. Members are never asked.'),
        ),
        migrations.AddField(
            model_name='whatsappenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
