# Generated by Django 5.2.12 on 2026-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0110_whatsapp_email_and_capture_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='level',
            field=models.CharField(choices=[('vip', 'VIP'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], db_index=True, default='vip', max_length=10),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='level_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
