# Generated by Django 5.2.12 on 2026-09-24 10:04
"""
The brand is one word: "Jackpotsworld", never "Jackpots World".

The code and translations were changed in the same commit; this rewrites the
same thing in the site content admins manage from the Back Office, which the
code change cannot reach -- landing copy, FAQs, events, promotions, support
scripts and the like. Measured locally before writing this: the separated name
was sitting in SupportScript, FAQ, LandingSettings and CasinoEvent rows.

Deliberately an allowlist of content models, not "every text column":
chat transcripts, enquiries, emails, notifications and logs are records of
what was actually said or sent, and rewriting them would falsify the record.

Only the separated spelling is touched ("Jackpots World", any case). The
long-standing "JackpotsWorld" spelling in page titles is a separate question
and is left alone. Slug, URL and email columns are skipped. Reverse is a
no-op: the old spelling is not something to restore.
"""
import re

from django.db import migrations, models

SEPARATED = re.compile(r"(?i)jackpots world")
REPLACEMENT = "Jackpotsworld"

CONTENT_MODELS = [
    "AndharBaharContent", "AndharBaharEvent", "AndharBaharHighlight", "AndharBaharStep",
    "CasinoEvent", "CruisePackage", "CruisePackageDetail", "Destination",
    "EnquiryMessage", "Experience", "FAQ", "FeaturedDestinationShowcase",
    "GiftItem", "GiftStep", "HeroStat", "LandingSettings", "PokerTournament",
    "PremiumPartner", "Promotion", "SupportDepartment", "SupportScript",
    "TeenPattiEvent", "Testimonial", "TourPackage", "TrustBadge", "VipTier",
    "VipTierBenefit", "VoiceCallSettings", "WhyChooseUsFeature",
]


def _text_fields(model):
    return [
        f.name for f in model._meta.fields
        if isinstance(f, (models.CharField, models.TextField))
        and not isinstance(f, (models.SlugField, models.URLField, models.EmailField))
        and not f.choices
    ]


def join_brand_name(apps, schema_editor):
    for name in CONTENT_MODELS:
        try:
            model = apps.get_model("authapp", name)
        except LookupError:
            continue
        fields = _text_fields(model)
        if not fields:
            continue
        query = models.Q()
        for f in fields:
            query |= models.Q(**{f"{f}__icontains": "jackpots world"})
        for row in model.objects.filter(query):
            changed = []
            for f in fields:
                value = getattr(row, f)
                if value and SEPARATED.search(value):
                    setattr(row, f, SEPARATED.sub(REPLACEMENT, value))
                    changed.append(f)
            if changed:
                # update_fields: never touch a column this did not rewrite.
                row.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0111_affiliate_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsettings',
            name='trust_banner_subtext',
            field=models.TextField(blank=True, default='From first-time casino visitors to high-rollers — Jackpotsworld is your trusted partner for every trip.'),
        ),
        migrations.RunPython(join_brand_name, migrations.RunPython.noop),
    ]
