# Generated by Django 5.2.12 on 2026-09-25 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0112_brand_name_one_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='level_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('wallet_credit', 'Wallet Credit'), ('wallet_debit', 'Wallet Debit'), ('wallet_adjusted', 'Wallet Adjusted'), ('deposit_created', 'Deposit Created'), ('withdrawal_created', 'Withdrawal Created'), ('casino_visit_recorded', 'Casino Visit Recorded'), ('casino_transfer', 'Casino Transfer'), ('rolling_points_rejected', 'Rolling Points Rejected'), ('bonus_added', 'Bonus Added'), ('reward_created', 'Reward Created'), ('reward_claimed', 'Reward Claimed'), ('vip_upgraded', 'VIP Upgraded'), ('vip_downgraded', 'VIP Downgraded'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('notification_sent', 'Notification Sent'), ('staff_created', 'Staff Created'), ('settings_changed', 'Settings Changed'), ('call_history_deleted', 'Call History Deleted'), ('two_factor_enabled', 'Two-Factor Enabled'), ('two_factor_disabled', 'Two-Factor Disabled'), ('affiliate_withdrawal_requested', 'Affiliate Withdrawal Requested'), ('affiliate_withdrawal_cancelled', 'Affiliate Withdrawal Cancelled'), ('affiliate_withdrawal_processing', 'Affiliate Withdrawal Moved To Processing'), ('affiliate_withdrawal_approved', 'Affiliate Withdrawal Approved'), ('affiliate_withdrawal_rejected', 'Affiliate Withdrawal Rejected'), ('affiliate_withdrawal_paid', 'Affiliate Withdrawal Paid'), ('affiliate_level_changed', 'Affiliate Level Changed'), ('main_deposit_requested', 'Deposit Request Submitted'), ('main_deposit_processing', 'Deposit Request Moved To Processing'), ('main_deposit_approved', 'Deposit Request Approved'), ('main_deposit_rejected', 'Deposit Request Rejected'), ('main_deposit_cancelled', 'Deposit Request Cancelled'), ('main_withdrawal_requested', 'Withdrawal Request Submitted'), ('main_withdrawal_processing', 'Withdrawal Request Moved To Processing'), ('main_withdrawal_approved', 'Withdrawal Request Approved'), ('main_withdrawal_rejected', 'Withdrawal Request Rejected'), ('main_withdrawal_paid', 'Withdrawal Request Paid'), ('main_withdrawal_cancelled', 'Withdrawal Request Cancelled'), ('gift_admin_created', 'Gift Created By Admin'), ('gift_expired', 'Gift Expired By Admin'), ('gift_cancelled', 'Gift Cancelled By Admin'), ('gift_reissued', 'Gift Reissued By Admin'), ('wheel_bonus_wheel_created', 'Bonus Wheel Created Or Edited'), ('wheel_bonus_assigned', 'Bonus Wheel Assigned To Players'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('rolling_points_added', 'Rolling Points Added'), ('admin_create', 'Admin Created A Record'), ('admin_update', 'Admin Updated A Record'), ('admin_delete', 'Admin Deleted A Record'), ('admin_action', 'Admin Action'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='AffiliateLevelCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=10, unique=True)),
                ('min_referred_players', models.PositiveIntegerField(blank=True, null=True)),
                ('min_qualified_players', models.PositiveIntegerField(blank=True, null=True)),
                ('min_deposit_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_commission_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
