# Generated by Django 5.2.12 on 2026-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0113_affiliate_level_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voiceover_audio', models.FileField(blank=True, max_length=255, null=True, upload_to='promotions/audio/')),
                ('voiceover_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
