"""
authapp/models/analytics_models.py
─────────────────────────────────────────────────────────────────────────────
ANALYTICS: first-party, privacy-conscious engagement analytics — real page
views, URL clicks, video engagement, signups and logins generated by actual
visitors, aggregated for the Admin Analytics dashboard.

This is a NEW, standalone system. It is deliberately independent of the
existing affiliate campaign/click-tracking system (AffiliateCampaign /
AffiliateClickLog), which keeps working exactly as before — general
marketing/UTM analytics and affiliate-referral analytics answer different
questions and must not be coupled. Safe to delete this module plus its import
block in models/__init__.py, analytics_serializers.py, analytics_service.py,
analytics_views.py and analytics_urls.py to remove the feature entirely.

Privacy posture (see also utils/anonymous_id.py):
  • No raw IP address is ever stored. IP is used transiently at ingest only to
    derive a salted, daily-rotating anonymous id when the client can't supply
    its own first-party id, to read Cloudflare's edge country header, and (for
    region/city — see services/analytics_service.py's _resolve_region_city) as
    input to the existing utils/geolocation.py lookup. Never persisted.
  • No passwords, payment data, tokens, message bodies or GPS/precise location
    — region/city is coarse (city-level at best, from IP, never device GPS).
  • Anonymous activity is never retroactively stitched to a member on login
    (approved decision): once anonymous, it stays anonymous.
"""
from django.conf import settings
from django.db import models
from django.utils import timezone


# ── Event vocabulary ─────────────────────────────────────────────────────────
# Kept as a plain list so new event types (button_click, destination_view, …)
# can be added later without a schema change — the column is a CharField, not
# an enum, and nothing downstream hard-codes this set except the choices label.
EVENT_PAGE_VIEW = "page_view"
EVENT_URL_CLICK = "url_click"
EVENT_VIDEO_START = "video_start"
EVENT_VIDEO_PROGRESS = "video_progress"
EVENT_VIDEO_COMPLETE = "video_complete"
# VIDEO-CLICK-ANALYTICS: two distinct click signals, both scoped to a video via
# the same (content_type="video", content_id=<video key>) addressing video_start
# already uses. Kept apart because they answer different questions and the
# admin dashboard reports both:
#   video_click     — a real user gesture on the player itself (tap on the
#                      poster/native controls to start or resume playback).
#   video_cta_click  — a click on a call-to-action associated with the video
#                      (e.g. a promotion's "Claim Bonus" button rendered next
#                      to its video). Not every video has one.
# Both are client-ingestable (see below) — unlike url_click, neither carries ad
# spend/attribution stakes, so there is no incentive to spoof them and no
# redirect-based server recording is needed the way Campaign links require.
EVENT_VIDEO_CLICK = "video_click"
EVENT_VIDEO_CTA_CLICK = "video_cta_click"
EVENT_SIGNUP = "signup"
EVENT_LOGIN = "login"

EVENT_TYPE_CHOICES = [
    (EVENT_PAGE_VIEW, "Page View"),
    (EVENT_URL_CLICK, "URL Click"),
    (EVENT_VIDEO_START, "Video Start"),
    (EVENT_VIDEO_PROGRESS, "Video Progress"),
    (EVENT_VIDEO_COMPLETE, "Video Complete"),
    (EVENT_VIDEO_CLICK, "Video Click"),
    (EVENT_VIDEO_CTA_CLICK, "Video CTA Click"),
    (EVENT_SIGNUP, "Signup"),
    (EVENT_LOGIN, "Login"),
]

# The event types a client is allowed to POST to /api/analytics/event. signup
# and login are emitted by the app on those actions (authenticated), url_click
# is recorded server-side by the redirect endpoint — so neither the click nor
# arbitrary types can be spoofed through the public ingest.
CLIENT_INGESTABLE_EVENT_TYPES = frozenset({
    EVENT_PAGE_VIEW,
    EVENT_VIDEO_START,
    EVENT_VIDEO_PROGRESS,
    EVENT_VIDEO_COMPLETE,
    EVENT_VIDEO_CLICK,
    EVENT_VIDEO_CTA_CLICK,
    EVENT_SIGNUP,
    EVENT_LOGIN,
})

# The milestones a video_progress event may report. 100 is included (not just
# the separate video_complete/"ended" event) so a viewer who scrubs straight to
# the end without the element ever firing `ended` still counts as complete —
# aggregation (_reduce_video) unions the two signals. The client de-dupes these
# per playback session (see useVideoAnalytics.js); aggregation also counts
# DISTINCT (session, video) per milestone, so a stray duplicate can never
# inflate a retention number even if one slips through.
VIDEO_MILESTONES = (25, 50, 75, 100)


class Campaign(models.Model):
    """A generic marketing campaign, identified by its UTM tuple. Separate
    from AffiliateCampaign on purpose (approved): this is for general
    marketing attribution (a banner on some partner site, an email blast),
    not an affiliate's personal referral bucket.

    Events carry their raw utm_* regardless of whether a Campaign row exists,
    so source/campaign analytics work even for traffic from a UTM that was
    never formally created here — a Campaign row just gives it a name, a
    trackable link, and a place to hang optional ad-cost later.
    """
    STATUS_ACTIVE = "active"
    STATUS_PAUSED = "paused"
    STATUS_ENDED = "ended"
    STATUS_CHOICES = [
        (STATUS_ACTIVE, "Active"),
        (STATUS_PAUSED, "Paused"),
        (STATUS_ENDED, "Ended"),
    ]

    name = models.CharField(max_length=150)

    # The UTM identity inbound traffic is matched on. utm_campaign is the
    # primary match key; the rest are recorded for display/filtering.
    utm_source = models.CharField(max_length=100, blank=True, db_index=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True, db_index=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    # For a trackable link: /api/analytics/click/<tracking_id> records a click
    # then 302s to destination_url. destination_url is backend-controlled (an
    # admin sets it), so the redirect can never be pointed at an arbitrary or
    # unsafe URL by a visitor.
    tracking_id = models.CharField(max_length=32, unique=True, db_index=True, blank=True)
    destination_url = models.CharField(max_length=500, blank=True)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=STATUS_ACTIVE, db_index=True)

    # ADVERTISING (§25): placeholders only. Left nullable and unused — no ROI
    # or revenue math is implemented, and none is invented. They exist so the
    # schema can carry ad spend later without a migration when real financial
    # inputs are available.
    ad_cost = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "utm_campaign"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.utm_campaign or self.tracking_id})"

    def save(self, *args, **kwargs):
        if not self.tracking_id:
            self.tracking_id = _unique_tracking_id()
        super().save(*args, **kwargs)


def _gen_tracking_id():
    import secrets
    return secrets.token_urlsafe(12)[:16]


def _unique_tracking_id():
    tid = _gen_tracking_id()
    while Campaign.objects.filter(tracking_id=tid).exists():
        tid = _gen_tracking_id()
    return tid


class AnalyticsEvent(models.Model):
    """One recorded interaction. Deliberately a single wide table rather than a
    table per event type: every dashboard query is "count/segment events of
    type X in a date window", which one well-indexed table answers directly,
    and new event types cost nothing.
    """
    event_type = models.CharField(max_length=32, choices=EVENT_TYPE_CHOICES, db_index=True)

    # Identity. `user` is the authenticated member, set ONLY from the request's
    # JWT server-side — never from the request body, so a client cannot claim
    # to be another user. `anonymous_id` is the visitor key when not logged in.
    # Exactly one is the identity for a given event; both may be blank for a
    # server-recorded event with no session (rare).
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="analytics_events",
    )
    anonymous_id = models.CharField(max_length=64, blank=True, db_index=True)
    session_id = models.CharField(max_length=64, blank=True, db_index=True)

    # VIDEO-CLICK-ANALYTICS: idempotency. A caller-generated key (see
    # services/analytics.js) identifying one logical user action — e.g. "this
    # exact click", "this playback session's start". A retry, a duplicate
    # React-effect fire, or a network-level resend of the same request carries
    # the SAME key, so record_event()'s get_or_create on (event_type,
    # client_event_id) makes the retry a no-op instead of a second row. A
    # second, genuinely separate click by the same visitor gets a NEW key
    # client-side, so it is correctly counted as a second click — this only
    # collapses accidental duplicates of one action, never real repeat
    # engagement.
    #
    # NULL, not "" — deliberately. The uniqueness guarantee below only works
    # if the many events that don't supply a key (every event type that
    # doesn't need one, and any older client build) don't collide with each
    # other. A blank string is one value, so a plain unique constraint on
    # thousands of ""s would fail immediately; NULL is standard-SQL "no value"
    # and is never considered equal to another NULL by a unique constraint, on
    # MySQL (production), SQLite (tests) or Postgres alike — so any number of
    # rows may leave this unset with no conflict. This also sidesteps
    # models.W036: MySQL does not support the *conditional* unique index that
    # would otherwise be needed to exempt blank strings, so a Q(...)-conditioned
    # constraint silently creates no constraint at all in production — the
    # exact failure mode NULL avoids.
    client_event_id = models.CharField(max_length=64, null=True, blank=True, db_index=True)

    # What the event is about. content_type is a coarse bucket ("video",
    # "page", "campaign"); content_id identifies the specific thing (a video
    # key, a route path). Free-form strings so any surface can emit without a
    # migration.
    content_type = models.CharField(max_length=40, blank=True, db_index=True)
    content_id = models.CharField(max_length=120, blank=True)

    url = models.CharField(max_length=500, blank=True)
    referrer = models.CharField(max_length=500, blank=True)
    source = models.CharField(max_length=120, blank=True)

    # Campaign attribution. `campaign` is resolved at ingest by matching
    # utm_campaign to a Campaign row (null when the UTM has no formal
    # campaign); the raw utm_* are always kept so grouping by source/campaign
    # works regardless.
    campaign = models.ForeignKey(
        Campaign, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="events",
    )
    utm_source = models.CharField(max_length=100, blank=True, db_index=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True, db_index=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    # Visitor context. Derived server-side from the User-Agent (device/browser/
    # os) and Cloudflare's edge country header — no raw IP is stored.
    device_type = models.CharField(max_length=20, blank=True)
    browser = models.CharField(max_length=40, blank=True)
    operating_system = models.CharField(max_length=40, blank=True)
    country = models.CharField(max_length=2, blank=True)  # ISO-3166 alpha-2

    # LOCATION-ANALYTICS: coarse, IP-derived, server-resolved only — never a
    # value the client can set (see analytics_serializers.py) and never GPS.
    # Blank means "not resolved" (e.g. a private/local IP, an unrecognised
    # value, or the lookup failing/timing out) and is rendered as "Unknown" by
    # the read side — see services/analytics_service.py's _resolve_region_city
    # for how these are populated and cached.
    region = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)

    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    # Extra per-event detail: video milestone percent, watched seconds,
    # duration, etc. Never carries anything sensitive (validated at ingest).
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            # Backs "events of type X over a window" (overview KPIs).
            models.Index(fields=["event_type", "created_at"]),
            # Backs per-video and per-page rollups.
            models.Index(fields=["content_type", "content_id", "event_type"]),
            # Backs campaign analytics.
            models.Index(fields=["campaign", "event_type", "created_at"]),
            models.Index(fields=["utm_campaign", "event_type"]),
            # Backs member-engagement lookups.
            models.Index(fields=["user", "event_type"]),
            models.Index(fields=["anonymous_id", "event_type"]),
            # VIDEO-CLICK-ANALYTICS: backs per-session lookups (e.g. the geo
            # cache's "has this session already been resolved" path) and
            # visitor-id-based unique counting keyed by session.
            models.Index(fields=["session_id", "event_type"]),
            # LOCATION-ANALYTICS: backs the country -> region -> city rollups.
            models.Index(fields=["country", "event_type"]),
        ]
        constraints = [
            # VIDEO-CLICK-ANALYTICS: the idempotency guarantee described in
            # client_event_id's field comment. Deliberately NOT conditioned on
            # client_event_id being non-blank (MySQL — production — rejects a
            # conditional unique constraint outright: see that comment). A
            # plain constraint works because the field is NULL, not "", when
            # absent, and NULL never collides with NULL in a unique index on
            # any of MySQL, SQLite or Postgres.
            models.UniqueConstraint(
                fields=["event_type", "client_event_id"],
                name="uniq_analyticsevent_type_client_id",
            ),
        ]

    def __str__(self):
        who = f"user:{self.user_id}" if self.user_id else f"anon:{self.anonymous_id[:8]}"
        return f"{self.event_type} · {who} · {self.created_at:%Y-%m-%d %H:%M}"
