"""
authapp/models/analytics_models.py
─────────────────────────────────────────────────────────────────────────────
ANALYTICS: first-party, privacy-conscious engagement analytics — real page
views, URL clicks, video engagement, signups and logins generated by actual
visitors, aggregated for the Admin Analytics dashboard.

This is a NEW, standalone system. It is deliberately independent of the
existing affiliate campaign/click-tracking system (AffiliateCampaign /
AffiliateClickLog), which keeps working exactly as before — general
marketing/UTM analytics and affiliate-referral analytics answer different
questions and must not be coupled. Safe to delete this module plus its import
block in models/__init__.py, analytics_serializers.py, analytics_service.py,
analytics_views.py and analytics_urls.py to remove the feature entirely.

Privacy posture (see also utils/anonymous_id.py):
  • IP ADDRESSES ARE STORED, on Visitor and VisitorSession only — never on
    AnalyticsEvent, which would multiply one visitor's address across every
    row they generate. This REVERSES the module's original "no raw IP is ever
    stored" stance, deliberately and on explicit instruction, because the
    Admin visitor list is required to show the address. What that costs and
    what bounds it:
      – Access: admin-only. The address is serialised by the admin analytics
        endpoints (IsAdminOrSuperAdmin) and by nothing else. No public API,
        no visitor-facing response, no page, no sitemap or SEO metadata ever
        includes it — see analytics_views.py, where the public ingest returns
        a bare {"recorded": n} and the redirect returns a 302 and nothing else.
      – Retention: ANALYTICS_IP_RETENTION_DAYS (default 90). Addresses older
        than that are cleared by the `prune_analytics_ips` management command,
        which blanks Visitor.ip_address/VisitorSession.ip_address in place and
        leaves every derived country/region/city intact — so the location
        analytics survive the address being forgotten. Run it from cron; it is
        idempotent and safe to run repeatedly.
      – Storage can be switched off entirely with ANALYTICS_STORE_IP=False,
        which keeps geolocation working (the address is still used transiently
        for the lookup) while persisting nothing.
  • No passwords, payment data, tokens, message bodies or GPS/precise location.
    Location is coarse and IP-derived (city-level at best) and is labelled
    "Approximate location" in the admin UI. The browser Geolocation API is
    never called — see utils/geolocation.py.
  • Anonymous activity is never retroactively stitched to a member on login
    (approved decision): once anonymous, it stays anonymous. Visitor therefore
    has NO foreign key to a user account — it identifies a browser, not a
    person, and joining the two would undo that decision by the back door.
"""
from django.conf import settings
from django.db import models
from django.utils import timezone


# ── Event vocabulary ─────────────────────────────────────────────────────────
# Kept as a plain list so new event types (button_click, destination_view, …)
# can be added later without a schema change — the column is a CharField, not
# an enum, and nothing downstream hard-codes this set except the choices label.
EVENT_PAGE_VIEW = "page_view"
EVENT_URL_CLICK = "url_click"
EVENT_VIDEO_START = "video_start"
EVENT_VIDEO_PROGRESS = "video_progress"
EVENT_VIDEO_COMPLETE = "video_complete"
# VIDEO-CLICK-ANALYTICS: two distinct click signals, both scoped to a video via
# the same (content_type="video", content_id=<video key>) addressing video_start
# already uses. Kept apart because they answer different questions and the
# admin dashboard reports both:
#   video_click     — a real user gesture on the player itself (tap on the
#                      poster/native controls to start or resume playback).
#   video_cta_click  — a click on a call-to-action associated with the video
#                      (e.g. a promotion's "Claim Bonus" button rendered next
#                      to its video). Not every video has one.
# Both are client-ingestable (see below) — unlike url_click, neither carries ad
# spend/attribution stakes, so there is no incentive to spoof them and no
# redirect-based server recording is needed the way Campaign links require.
EVENT_VIDEO_CLICK = "video_click"
EVENT_VIDEO_CTA_CLICK = "video_cta_click"
# VISITOR-ANALYTICS: the general element click. url_click stays what it always
# was — a server-recorded campaign-redirect click, never client-ingestable,
# because it carries ad-spend/attribution stakes. This one is the ordinary
# "a visitor clicked a tracked button or link" signal the click dashboard
# counts, and it IS client-ingestable: it has no spend attached, and it is
# protected against miscounting by client_event_id idempotency rather than by
# refusing client input.
EVENT_CLICK = "click"
# VISITOR-ANALYTICS: video engagement beyond start/progress/complete. An
# impression is "the player was actually rendered/visible", which is what
# makes a view-through rate meaningful — without it there is no denominator
# separating "never saw the video" from "saw it and didn't play it".
EVENT_VIDEO_IMPRESSION = "video_impression"
EVENT_VIDEO_PAUSE = "video_pause"
EVENT_VIDEO_EXIT = "video_exit"
EVENT_SIGNUP = "signup"
EVENT_LOGIN = "login"

EVENT_TYPE_CHOICES = [
    (EVENT_PAGE_VIEW, "Page View"),
    (EVENT_URL_CLICK, "URL Click"),
    (EVENT_CLICK, "Click"),
    (EVENT_VIDEO_IMPRESSION, "Video Impression"),
    (EVENT_VIDEO_START, "Video Start"),
    (EVENT_VIDEO_PROGRESS, "Video Progress"),
    (EVENT_VIDEO_COMPLETE, "Video Complete"),
    (EVENT_VIDEO_PAUSE, "Video Pause"),
    (EVENT_VIDEO_EXIT, "Video Exit"),
    (EVENT_VIDEO_CLICK, "Video Click"),
    (EVENT_VIDEO_CTA_CLICK, "Video CTA Click"),
    (EVENT_SIGNUP, "Signup"),
    (EVENT_LOGIN, "Login"),
]

# The event types a client is allowed to POST to /api/analytics/event. signup
# and login are emitted by the app on those actions (authenticated), url_click
# is recorded server-side by the redirect endpoint — so neither the click nor
# arbitrary types can be spoofed through the public ingest.
CLIENT_INGESTABLE_EVENT_TYPES = frozenset({
    EVENT_PAGE_VIEW,
    EVENT_CLICK,
    EVENT_VIDEO_IMPRESSION,
    EVENT_VIDEO_START,
    EVENT_VIDEO_PROGRESS,
    EVENT_VIDEO_COMPLETE,
    EVENT_VIDEO_PAUSE,
    EVENT_VIDEO_EXIT,
    EVENT_VIDEO_CLICK,
    EVENT_VIDEO_CTA_CLICK,
    EVENT_SIGNUP,
    EVENT_LOGIN,
})

# Named here rather than inline at each call site so the read side and the
# write side can never drift apart on what counts as a click.
# Every kind of click, for "how many clicks did we get" — which means all of
# them, not just the campaign-redirect ones the dashboard used to count.
# Video events are NOT listed as a set here: they are already addressed by
# content_type="video", which is how every video query in this module scopes
# itself, and a second overlapping definition would be one more thing that can
# drift out of step.
CLICK_EVENT_TYPES = frozenset({EVENT_CLICK, EVENT_URL_CLICK, EVENT_VIDEO_CLICK, EVENT_VIDEO_CTA_CLICK})

# Geolocation outcome recorded against a Visitor/VisitorSession. Mirrors
# utils/geolocation.py's status vocabulary exactly — a blank country with
# status "private_ip" means something completely different to the admin
# reading it than a blank country with status "failed", and collapsing both
# to "Unknown" is what made the current dashboard impossible to debug.
GEO_STATUS_SUCCESS = "success"
GEO_STATUS_FAILED = "failed"
GEO_STATUS_PRIVATE_IP = "private_ip"
GEO_STATUS_UNAVAILABLE = "unavailable"
GEO_STATUS_CHOICES = [
    (GEO_STATUS_SUCCESS, "Success"),
    (GEO_STATUS_FAILED, "Failed"),
    (GEO_STATUS_PRIVATE_IP, "Private / local IP"),
    (GEO_STATUS_UNAVAILABLE, "Unavailable"),
]

# The milestones a video_progress event may report. 100 is included (not just
# the separate video_complete/"ended" event) so a viewer who scrubs straight to
# the end without the element ever firing `ended` still counts as complete —
# aggregation (_reduce_video) unions the two signals. The client de-dupes these
# per playback session (see useVideoAnalytics.js); aggregation also counts
# DISTINCT (session, video) per milestone, so a stray duplicate can never
# inflate a retention number even if one slips through.
VIDEO_MILESTONES = (25, 50, 75, 100)


class Campaign(models.Model):
    """A generic marketing campaign, identified by its UTM tuple. Separate
    from AffiliateCampaign on purpose (approved): this is for general
    marketing attribution (a banner on some partner site, an email blast),
    not an affiliate's personal referral bucket.

    Events carry their raw utm_* regardless of whether a Campaign row exists,
    so source/campaign analytics work even for traffic from a UTM that was
    never formally created here — a Campaign row just gives it a name, a
    trackable link, and a place to hang optional ad-cost later.
    """
    STATUS_ACTIVE = "active"
    STATUS_PAUSED = "paused"
    STATUS_ENDED = "ended"
    STATUS_CHOICES = [
        (STATUS_ACTIVE, "Active"),
        (STATUS_PAUSED, "Paused"),
        (STATUS_ENDED, "Ended"),
    ]

    name = models.CharField(max_length=150)

    # The UTM identity inbound traffic is matched on. utm_campaign is the
    # primary match key; the rest are recorded for display/filtering.
    utm_source = models.CharField(max_length=100, blank=True, db_index=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True, db_index=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    # For a trackable link: /api/analytics/click/<tracking_id> records a click
    # then 302s to destination_url. destination_url is backend-controlled (an
    # admin sets it), so the redirect can never be pointed at an arbitrary or
    # unsafe URL by a visitor.
    tracking_id = models.CharField(max_length=32, unique=True, db_index=True, blank=True)
    destination_url = models.CharField(max_length=500, blank=True)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=STATUS_ACTIVE, db_index=True)

    # ADVERTISING (§25): placeholders only. Left nullable and unused — no ROI
    # or revenue math is implemented, and none is invented. They exist so the
    # schema can carry ad spend later without a migration when real financial
    # inputs are available.
    ad_cost = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "utm_campaign"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.utm_campaign or self.tracking_id})"

    def save(self, *args, **kwargs):
        if not self.tracking_id:
            self.tracking_id = _unique_tracking_id()
        super().save(*args, **kwargs)


def _gen_tracking_id():
    import secrets
    return secrets.token_urlsafe(12)[:16]


def _unique_tracking_id():
    tid = _gen_tracking_id()
    while Campaign.objects.filter(tracking_id=tid).exists():
        tid = _gen_tracking_id()
    return tid


class GeoSnapshot(models.Model):
    """The approximate, IP-derived location fields shared by Visitor and
    VisitorSession. Abstract — it adds no table of its own.

    Both models carry their own copy rather than pointing at a shared row, and
    that duplication is the point: a visitor who travels (or changes ISP)
    gets a NEW session with a NEW snapshot, while their earlier sessions keep
    the location they actually had at the time. A single mutable location on
    Visitor alone would silently rewrite history — last week's video viewers
    would appear to have watched from wherever the person is today.

    Every field is blank/NULL when unresolved. Nothing here is ever defaulted
    to a plausible-looking value: a blank city means the lookup did not return
    a city, and `geo_status` says why.
    """
    # ISO-3166 alpha-2 ("IN"), and the provider's full name ("India"). Both,
    # because the code is what filters/groups reliably and the name is what an
    # admin reads — deriving one from the other would need a country table
    # this project does not have.
    country_code = models.CharField(max_length=2, blank=True, db_index=True)
    country_name = models.CharField(max_length=100, blank=True)
    region = models.CharField(max_length=100, blank=True)
    region_code = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=100, blank=True)
    timezone_name = models.CharField(max_length=64, blank=True)

    # City-centroid coordinates from the IP lookup. NOT a device position —
    # see utils/geolocation.py. Nullable rather than 0.0 so "no fix" is
    # distinguishable from "the equator".
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    # Network operator, when the provider supplies one. Coarse and often the
    # transit provider rather than the retail ISP, so it is displayed as
    # supplementary detail and never used for counting.
    isp = models.CharField(max_length=120, blank=True)

    geo_status = models.CharField(
        max_length=16, choices=GEO_STATUS_CHOICES, blank=True, db_index=True,
    )

    class Meta:
        abstract = True

    @property
    def has_location(self):
        return self.geo_status == GEO_STATUS_SUCCESS

    def location_label(self):
        """Human-readable location, honest about what is actually known.
        Never invents a country or city to fill a gap."""
        if self.geo_status == GEO_STATUS_PRIVATE_IP:
            return "Local / Private Network"
        parts = [p for p in (self.city, self.region, self.country_name) if p]
        return ", ".join(parts) if parts else "Unknown"


class Visitor(GeoSnapshot):
    """One browser, tracked across sessions by its first-party visitor id.

    NOT a person and NOT an IP. Deliberately keyed on the opaque random token
    the browser stores in localStorage (utils/anonymous_id.py), because the
    two obvious alternatives are both wrong: an IP is shared by everyone
    behind a NAT and changes under one person as they move between networks,
    and a cookie-less server-side fingerprint would be neither stable nor
    privacy-safe. See services/analytics.js for the client half.
    """
    visitor_id = models.CharField(max_length=64, unique=True, db_index=True)

    first_seen = models.DateTimeField(default=timezone.now, db_index=True)
    last_seen = models.DateTimeField(default=timezone.now, db_index=True)

    # Most recent address seen for this visitor. Admin-only, retention-bounded,
    # clearable — see the module docstring. NULL means either "never captured"
    # or "aged out of retention"; the derived location fields stay either way.
    ip_address = models.GenericIPAddressField(null=True, blank=True)

    # Latest device fingerprint-ish context, from the User-Agent only.
    device_type = models.CharField(max_length=20, blank=True)
    browser = models.CharField(max_length=40, blank=True)
    operating_system = models.CharField(max_length=40, blank=True)

    # First-touch acquisition, written once at creation and never overwritten —
    # the campaign that actually won the visitor must not be rewritten by
    # wherever they happened to arrive from on a later visit.
    first_referrer = models.CharField(max_length=500, blank=True)
    landing_page = models.CharField(max_length=500, blank=True)
    traffic_source = models.CharField(max_length=60, blank=True, db_index=True)
    utm_source = models.CharField(max_length=100, blank=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ["-last_seen"]
        indexes = [
            # Backs the "recent visitors" list and every date-window filter.
            models.Index(fields=["-last_seen"]),
            # Backs "new visitors in this window".
            models.Index(fields=["first_seen"]),
            # Backs the country -> region -> city rollups and admin filters.
            models.Index(fields=["country_code", "last_seen"]),
        ]

    def __str__(self):
        return f"visitor {self.short_id} · {self.location_label()}"

    @property
    def short_id(self):
        """The 6-character handle the admin UI shows instead of a 32-char
        token — matches the brief's "8A92F1" style."""
        return self.visitor_id[-6:].upper()


class VisitorSession(GeoSnapshot):
    """One browsing session for a Visitor.

    A session is continued rather than recreated while the visitor keeps
    navigating: the client holds its session id in sessionStorage (so it
    survives route changes and reloads but not a closed tab), and the server
    additionally expires one after SESSION_IDLE_MINUTES of inactivity, so a
    tab left open overnight starts a new session in the morning instead of
    reporting one 14-hour visit.
    """
    session_id = models.CharField(max_length=64, unique=True, db_index=True)
    visitor = models.ForeignKey(
        Visitor, on_delete=models.CASCADE, related_name="sessions",
    )

    started_at = models.DateTimeField(default=timezone.now, db_index=True)
    last_activity_at = models.DateTimeField(default=timezone.now, db_index=True)

    ip_address = models.GenericIPAddressField(null=True, blank=True)

    device_type = models.CharField(max_length=20, blank=True)
    browser = models.CharField(max_length=40, blank=True)
    operating_system = models.CharField(max_length=40, blank=True)

    # Per-session acquisition — unlike Visitor's, this one describes THIS
    # visit, so a returning visitor arriving from a different campaign is
    # attributed correctly for that visit.
    referrer = models.CharField(max_length=500, blank=True)
    landing_page = models.CharField(max_length=500, blank=True)
    traffic_source = models.CharField(max_length=60, blank=True, db_index=True)
    utm_source = models.CharField(max_length=100, blank=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ["-last_activity_at"]
        indexes = [
            models.Index(fields=["visitor", "-started_at"]),
            models.Index(fields=["-last_activity_at"]),
            models.Index(fields=["country_code", "started_at"]),
        ]

    def __str__(self):
        return f"session {self.session_id[-6:]} · visitor {self.visitor_id}"


class AnalyticsEvent(models.Model):
    """One recorded interaction. Deliberately a single wide table rather than a
    table per event type: every dashboard query is "count/segment events of
    type X in a date window", which one well-indexed table answers directly,
    and new event types cost nothing.
    """
    event_type = models.CharField(max_length=32, choices=EVENT_TYPE_CHOICES, db_index=True)

    # Identity. `user` is the authenticated member, set ONLY from the request's
    # JWT server-side — never from the request body, so a client cannot claim
    # to be another user. `anonymous_id` is the visitor key when not logged in.
    # Exactly one is the identity for a given event; both may be blank for a
    # server-recorded event with no session (rare).
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="analytics_events",
    )
    anonymous_id = models.CharField(max_length=64, blank=True, db_index=True)
    session_id = models.CharField(max_length=64, blank=True, db_index=True)

    # VISITOR-ANALYTICS: the resolved rows behind those two string keys.
    # The strings stay — they are what the client sends and what every
    # existing aggregation groups on — and these are added alongside so the
    # admin can walk from an event to the visitor's location/timeline without
    # a second lookup keyed on a string. SET_NULL rather than CASCADE: pruning
    # a visitor must never silently delete their events and change historical
    # counts.
    visitor = models.ForeignKey(
        "authapp.Visitor", null=True, blank=True,
        on_delete=models.SET_NULL, related_name="events",
    )
    # Named `visitor_session`, not `session`: a FK called `session` would want
    # the column `session_id`, which is already taken by the client-supplied
    # string key above (models.E006).
    visitor_session = models.ForeignKey(
        "authapp.VisitorSession", null=True, blank=True,
        on_delete=models.SET_NULL, related_name="events",
    )

    # VIDEO-CLICK-ANALYTICS: idempotency. A caller-generated key (see
    # services/analytics.js) identifying one logical user action — e.g. "this
    # exact click", "this playback session's start". A retry, a duplicate
    # React-effect fire, or a network-level resend of the same request carries
    # the SAME key, so record_event()'s get_or_create on (event_type,
    # client_event_id) makes the retry a no-op instead of a second row. A
    # second, genuinely separate click by the same visitor gets a NEW key
    # client-side, so it is correctly counted as a second click — this only
    # collapses accidental duplicates of one action, never real repeat
    # engagement.
    #
    # NULL, not "" — deliberately. The uniqueness guarantee below only works
    # if the many events that don't supply a key (every event type that
    # doesn't need one, and any older client build) don't collide with each
    # other. A blank string is one value, so a plain unique constraint on
    # thousands of ""s would fail immediately; NULL is standard-SQL "no value"
    # and is never considered equal to another NULL by a unique constraint, on
    # MySQL (production), SQLite (tests) or Postgres alike — so any number of
    # rows may leave this unset with no conflict. This also sidesteps
    # models.W036: MySQL does not support the *conditional* unique index that
    # would otherwise be needed to exempt blank strings, so a Q(...)-conditioned
    # constraint silently creates no constraint at all in production — the
    # exact failure mode NULL avoids.
    client_event_id = models.CharField(max_length=64, null=True, blank=True, db_index=True)

    # What the event is about. content_type is a coarse bucket ("video",
    # "page", "campaign"); content_id identifies the specific thing (a video
    # key, a route path). Free-form strings so any surface can emit without a
    # migration.
    content_type = models.CharField(max_length=40, blank=True, db_index=True)
    content_id = models.CharField(max_length=120, blank=True)

    url = models.CharField(max_length=500, blank=True)
    referrer = models.CharField(max_length=500, blank=True)
    source = models.CharField(max_length=120, blank=True)

    # VISITOR-ANALYTICS: what was clicked, for EVENT_CLICK. All blank for every
    # other event type. element_label is the visible text (trimmed) so the
    # click dashboard can name a button without the admin having to decode an
    # id; destination_url is where the click was headed, for links.
    element_id = models.CharField(max_length=120, blank=True, db_index=True)
    element_type = models.CharField(max_length=40, blank=True)
    element_label = models.CharField(max_length=200, blank=True)
    destination_url = models.CharField(max_length=500, blank=True)

    # Campaign attribution. `campaign` is resolved at ingest by matching
    # utm_campaign to a Campaign row (null when the UTM has no formal
    # campaign); the raw utm_* are always kept so grouping by source/campaign
    # works regardless.
    campaign = models.ForeignKey(
        Campaign, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="events",
    )
    utm_source = models.CharField(max_length=100, blank=True, db_index=True)
    utm_medium = models.CharField(max_length=100, blank=True)
    utm_campaign = models.CharField(max_length=150, blank=True, db_index=True)
    utm_content = models.CharField(max_length=150, blank=True)
    utm_term = models.CharField(max_length=150, blank=True)

    # Visitor context. Derived server-side from the User-Agent (device/browser/
    # os) and Cloudflare's edge country header — no raw IP is stored.
    device_type = models.CharField(max_length=20, blank=True)
    browser = models.CharField(max_length=40, blank=True)
    operating_system = models.CharField(max_length=40, blank=True)
    country = models.CharField(max_length=2, blank=True)  # ISO-3166 alpha-2
    # The country's display name, denormalised alongside the code so a rollup
    # can label a row without joining Visitor. Blank when unresolved — never
    # back-filled with a guess.
    country_name = models.CharField(max_length=100, blank=True)

    # LOCATION-ANALYTICS: coarse, IP-derived, server-resolved only — never a
    # value the client can set (see analytics_serializers.py) and never GPS.
    # Blank means "not resolved" (e.g. a private/local IP, an unrecognised
    # value, or the lookup failing/timing out) and is rendered as "Unknown" by
    # the read side — see services/analytics_service.py's _resolve_region_city
    # for how these are populated and cached.
    region = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)

    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    # Extra per-event detail: video milestone percent, watched seconds,
    # duration, etc. Never carries anything sensitive (validated at ingest).
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            # Backs "events of type X over a window" (overview KPIs).
            models.Index(fields=["event_type", "created_at"]),
            # Backs per-video and per-page rollups.
            models.Index(fields=["content_type", "content_id", "event_type"]),
            # Backs campaign analytics.
            models.Index(fields=["campaign", "event_type", "created_at"]),
            models.Index(fields=["utm_campaign", "event_type"]),
            # Backs member-engagement lookups.
            models.Index(fields=["user", "event_type"]),
            models.Index(fields=["anonymous_id", "event_type"]),
            # VIDEO-CLICK-ANALYTICS: backs per-session lookups (e.g. the geo
            # cache's "has this session already been resolved" path) and
            # visitor-id-based unique counting keyed by session.
            models.Index(fields=["session_id", "event_type"]),
            # LOCATION-ANALYTICS: backs the country -> region -> city rollups.
            models.Index(fields=["country", "event_type"]),
            # VISITOR-ANALYTICS: backs the per-visitor timeline (ordered by
            # time, scoped to one visitor) and the per-session event lists.
            models.Index(fields=["visitor", "created_at"]),
            models.Index(fields=["visitor_session", "created_at"]),
            # Backs "clicks by element" on the click dashboard.
            models.Index(fields=["element_id", "event_type"]),
        ]
        constraints = [
            # VIDEO-CLICK-ANALYTICS: the idempotency guarantee described in
            # client_event_id's field comment. Deliberately NOT conditioned on
            # client_event_id being non-blank (MySQL — production — rejects a
            # conditional unique constraint outright: see that comment). A
            # plain constraint works because the field is NULL, not "", when
            # absent, and NULL never collides with NULL in a unique index on
            # any of MySQL, SQLite or Postgres.
            models.UniqueConstraint(
                fields=["event_type", "client_event_id"],
                name="uniq_analyticsevent_type_client_id",
            ),
        ]

    def __str__(self):
        who = f"user:{self.user_id}" if self.user_id else f"anon:{self.anonymous_id[:8]}"
        return f"{self.event_type} · {who} · {self.created_at:%Y-%m-%d %H:%M}"
